/* Crēdo Legal — Nextdoor Ads page data. GENERATED by scripts/nextdoor/build-ads-data.js from
 * handoff/nextdoor/ (manifest + copy CSVs + asset manifest) — edit those, then rebuild.
 * The metrics block is preserved across rebuilds and updated by the weekly metrics task. */
window.CREDO_ND_ADS = {
 "generated": "2026-09-17T18:42:27.834Z",
 "family": "Credo Legal — Debt Validation (Nextdoor) v1",
 "prepared": "2026-08-21",
 "status": "PAUSED",
 "scope": {
  "launch_states": [
   "New York",
   "New Jersey"
  ],
  "allowed_topics": "debt validation / invalidation + settlement only",
  "excluded_topics": [
   "litigation",
   "lawsuit",
   "garnishment",
   "judgment",
   "payday"
  ],
  "notes": "Clean-file experiment. Nextdoor PROHIBITS payday-loan ads and RESTRICTS 'debt services'; position strictly as LEGAL REPRESENTATION (attorneys who make collectors validate the debt), never as debt settlement/relief or a 'reduce what you owe by X%' product. Get WRITTEN sign-off from Nextdoor ad review on (a) attorney-advertising eligibility and (b) legal-services (not debt-services) classification BEFORE any spend."
 },
 "campaigns": [
  {
   "name": "Credo Legal — Validation Leads (Nextdoor)",
   "objective": "LEAD_GENERATION",
   "primary": true,
   "utm_campaign": "credo_nd_leadgen_v1",
   "destination": "nextdoor_native_lead_form",
   "notes": "Recommended primary for a sensitive, real-name feed: private, pre-filled from verified neighbor data, no click-off."
  },
  {
   "name": "Credo Legal — Validation Traffic (Nextdoor)",
   "objective": "WEBSITE_CLICKS",
   "primary": false,
   "utm_campaign": "credo_nd_traffic_v1",
   "destination": "cluster_landing_page",
   "notes": "Secondary path for the fuller LP experience. Same ad groups / ads / creatives as the lead-gen campaign."
  }
 ],
 "utm": {
  "utm_source": "nextdoor",
  "utm_medium": "paid_social",
  "utm_campaign": "credo_nd_{objective}_v1  (leadgen | traffic | awareness | conversions)",
  "utm_term": "{cluster}  (validation | medical | credit-card)",
  "utm_content": "{ad}-{direction}  (e.g. fdcpa-rights-photo; ad-level value omits -{direction})",
  "conventions": "all lowercase; hyphens inside a token; underscores only between the structural parts of utm_campaign; one utm_medium value forever.",
  "click_id": "ndclid (Nextdoor-appended on the destination URL — never strip or reorder)"
 },
 "targeting": {
  "geo": "United States, scoped to New York and New Jersey only (per launch scope). Broad-geo first, then narrow — many members leave age/gender blank and get silently excluded by over-restriction.",
  "demographic": "Skews homeowner, 35+, household income $75K+, suburban. Layer homeownership / income / age lightly; do NOT target under-18; do NOT assert or imply protected attributes (Nextdoor restricted-financial rule).",
  "audiences": "Upload existing clients to EXCLUDE; build lookalikes from best customers; retarget Google/Meta LP visitors via the Nextdoor Pixel.",
  "excluded": [
   "existing clients",
   "under-18"
  ]
 },
 "budget": {
  "monthly_test_line": "~$5,000/mo, disciplined test (Nextdoor is a secondary/unproven channel for this vertical).",
  "cpc": "Real-world local $2.50-$3.50 (directional). Use odd-cent bids (e.g. $3.01).",
  "cpm": "Suggested start ~$10.01; adjust +/- $0.25 every ~10 days.",
  "bid_to_daily_ratio": "Keep 5-10x bid-to-daily-budget so delivery is not starved (e.g. $10 bid -> $75-100/day). Start higher to learn, then taper."
 },
 "tracking": {
  "pixel": "Nextdoor Universal Pixel on every LP (via tag manager) + Conversion API (CAPI) server-side. Events: lead, purchase, custom.",
  "call_tracking": "Pixel MISSES phone-call leads — wire a dedicated per-cluster DNI call number so calls are attributed.",
  "crm": "Zapier (or Hightouch) auto-routes captured leads into the CRM/stub.",
  "retention": "Nextdoor keeps 30 days of report data — export before the window closes.",
  "preserve": "ndclid on all click-to-website destinations."
 },
 "compliance": {
  "new_jersey": "Include responsible attorney's name (Jack [CONFIRM full name]) and firm contact (mailing address, phone, email). No pre-filing requirement.",
  "new_york": "Additionally: (a) 'Attorney Advertising' label, (b) attorney (Jack) PRE-APPROVAL of every ad before it goes live, (c) AI-generated-content disclosure. All copy is AI-drafted -> humanize + Jack's review before launch.",
  "universal_footer": "Crēdo Legal. The choice of a lawyer is an important decision and should not be based solely upon advertisements.",
  "results_disclaimer": "Prior outcomes don't guarantee similar results.",
  "creative_exclusions": "Bold red-gesture creative stays OUT of Nextdoor (reads aggressive/salesy; the community downvotes it). No 9:16 (Nextdoor uses 1:1 and 1.91:1). Logos hurt CTR here (-14%) — keep brand present but understated while still visible per policy.",
  "confirm": [
   "Jack full name",
   "firm mailing address",
   "firm phone",
   "firm email",
   "exact NY AI-disclosure wording",
   "privacy-policy URL for the lead form",
   "testimonial/recommendation rules"
  ]
 },
 "headlines": [
  "Get a Free Review of Your Case",
  "Know Your Options, Free",
  "See If They Can Even Prove It, Free",
  "You Don't Have to Face Them Alone",
  "Make Them Prove You Owe It",
  "A Free Case Review, No Cost to You"
 ],
 "clusters": [
  {
   "key": "validation",
   "label": "Debt validation",
   "landingPage": "https://start.credolegal.com/debt-harassment-stop-calls",
   "ads": [
    {
     "key": "creditor-harassment",
     "topic": "Collection calls — make them validate",
     "headline": "Get a Free Review of Your Case",
     "cta": "Get a Free Review",
     "finalUrl": "https://start.credolegal.com/debt-harassment-stop-calls",
     "finalUrlUtm": "https://start.credolegal.com/debt-harassment-stop-calls?utm_source=nextdoor&utm_medium=paid_social&utm_campaign=credo_nd_traffic_v1&utm_term=validation&utm_content=creditor-harassment",
     "bodies": [
      {
       "variant": "Default",
       "text": "Getting collection calls about a debt? You can make them prove it is yours in writing before you pay a cent. Many collectors, especially debt buyers, cannot produce the paperwork. Our attorneys can send the request and review what comes back. Free case review.",
       "footer": "Attorney Advertising. Prior outcomes don't guarantee similar results. Crēdo Legal — responsible attorney Jack [CONFIRM], licensed in NY & NJ. [firm mailing address · phone · email — CONFIRM]. Includes AI-generated content. The choice of a lawyer is an important decision and should not be based solely upon advertisements."
      },
      {
       "variant": "Reassurance",
       "text": "You do not have to handle a collector alone. You can require them to validate the debt in writing first, and you may owe far less than they claim. A free review shows exactly where you stand.",
       "footer": "Attorney Advertising. Prior outcomes don't guarantee similar results. Crēdo Legal — responsible attorney Jack [CONFIRM], licensed in NY & NJ. [firm mailing address · phone · email — CONFIRM]. Includes AI-generated content. The choice of a lawyer is an important decision and should not be based solely upon advertisements."
      }
     ],
     "creatives": [
      {
       "direction": "illustration",
       "utm_content": "creditor-harassment-illustration",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/Creditor_Harassment_D1_Illustration_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/Creditor_Harassment_D1_Illustration_1_91x1.png"
       }
      },
      {
       "direction": "photo",
       "utm_content": "creditor-harassment-photo",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/Creditor_Harassment_D2_Photo_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/Creditor_Harassment_D2_Photo_1_91x1.png"
       }
      },
      {
       "direction": "stilllife",
       "utm_content": "creditor-harassment-stilllife",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/Creditor_Harassment_D3_StillLife_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/Creditor_Harassment_D3_StillLife_1_91x1.png"
       }
      }
     ]
    },
    {
     "key": "fdcpa-rights",
     "topic": "Know your rights — 3 things collectors hope you don't know",
     "headline": "See If They Can Even Prove It, Free",
     "cta": "Get a Free Review",
     "finalUrl": "https://start.credolegal.com/debt-harassment-stop-calls",
     "finalUrlUtm": "https://start.credolegal.com/debt-harassment-stop-calls?utm_source=nextdoor&utm_medium=paid_social&utm_campaign=credo_nd_traffic_v1&utm_term=validation&utm_content=fdcpa-rights",
     "bodies": [
      {
       "variant": "Default",
       "text": "Three things collectors hope you do not know: you can make them validate the debt, debt buyers often cannot prove they own it, and balances are frequently inflated. Know your rights before you respond. Free case review.",
       "footer": "Attorney Advertising. Prior outcomes don't guarantee similar results. Crēdo Legal — responsible attorney Jack [CONFIRM], licensed in NY & NJ. [firm mailing address · phone · email — CONFIRM]. Includes AI-generated content. The choice of a lawyer is an important decision and should not be based solely upon advertisements."
      },
      {
       "variant": "Reassurance",
       "text": "Know the rules before you answer a collector. Federal law limits what they can do, and you can demand written proof of the debt first. Our attorneys can walk you through it. Free case review.",
       "footer": "Attorney Advertising. Prior outcomes don't guarantee similar results. Crēdo Legal — responsible attorney Jack [CONFIRM], licensed in NY & NJ. [firm mailing address · phone · email — CONFIRM]. Includes AI-generated content. The choice of a lawyer is an important decision and should not be based solely upon advertisements."
      }
     ],
     "creatives": [
      {
       "direction": "illustration",
       "utm_content": "fdcpa-rights-illustration",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/FDCPA_Harassment_D1_Illustration_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/FDCPA_Harassment_D1_Illustration_1_91x1.png"
       }
      },
      {
       "direction": "photo",
       "utm_content": "fdcpa-rights-photo",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/FDCPA_Harassment_D2_Photo_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/FDCPA_Harassment_D2_Photo_1_91x1.png"
       }
      },
      {
       "direction": "stilllife",
       "utm_content": "fdcpa-rights-stilllife",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/FDCPA_Harassment_D3_StillLife_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/FDCPA_Harassment_D3_StillLife_1_91x1.png"
       }
      }
     ]
    },
    {
     "key": "multiple-collectors",
     "topic": "Several collectors, one debt — who can actually collect?",
     "headline": "You Don't Have to Face Them Alone",
     "cta": "Get a Free Review",
     "finalUrl": "https://start.credolegal.com/debt-harassment-stop-calls",
     "finalUrlUtm": "https://start.credolegal.com/debt-harassment-stop-calls?utm_source=nextdoor&utm_medium=paid_social&utm_campaign=credo_nd_traffic_v1&utm_term=validation&utm_content=multiple-collectors",
     "bodies": [
      {
       "variant": "Default",
       "text": "More than one collector chasing the same debt? Each has to validate it in writing if you ask, and the paperwork often does not hold up. Our attorneys can sort out who, if anyone, can actually collect. Free review.",
       "footer": "Attorney Advertising. Prior outcomes don't guarantee similar results. Crēdo Legal — responsible attorney Jack [CONFIRM], licensed in NY & NJ. [firm mailing address · phone · email — CONFIRM]. Includes AI-generated content. The choice of a lawyer is an important decision and should not be based solely upon advertisements."
      },
      {
       "variant": "Reassurance",
       "text": "Several collectors at once is overwhelming, but you have options. You can make each one prove the debt is valid before paying anything. A free review can bring order to it.",
       "footer": "Attorney Advertising. Prior outcomes don't guarantee similar results. Crēdo Legal — responsible attorney Jack [CONFIRM], licensed in NY & NJ. [firm mailing address · phone · email — CONFIRM]. Includes AI-generated content. The choice of a lawyer is an important decision and should not be based solely upon advertisements."
      }
     ],
     "creatives": [
      {
       "direction": "illustration",
       "utm_content": "multiple-collectors-illustration",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/Multiple_Collectors_D1_Illustration_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/Multiple_Collectors_D1_Illustration_1_91x1.png"
       }
      },
      {
       "direction": "photo",
       "utm_content": "multiple-collectors-photo",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/Multiple_Collectors_D2_Photo_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/Multiple_Collectors_D2_Photo_1_91x1.png"
       }
      },
      {
       "direction": "stilllife",
       "utm_content": "multiple-collectors-stilllife",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/Multiple_Collectors_D3_StillLife_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/harassment/v3-pilot/Multiple_Collectors_D3_StillLife_1_91x1.png"
       }
      }
     ]
    }
   ]
  },
  {
   "key": "medical",
   "label": "Medical debt",
   "landingPage": "https://start.credolegal.com/medical-debt-bills-errors",
   "ads": [
    {
     "key": "medical-validation",
     "topic": "A collector says you owe it — can they prove it?",
     "headline": "See If They Can Even Prove It, Free",
     "cta": "Get a Free Review",
     "finalUrl": "https://start.credolegal.com/medical-debt-bills-errors",
     "finalUrlUtm": "https://start.credolegal.com/medical-debt-bills-errors?utm_source=nextdoor&utm_medium=paid_social&utm_campaign=credo_nd_traffic_v1&utm_term=medical&utm_content=medical-validation",
     "bodies": [
      {
       "variant": "Default",
       "text": "A collector says you owe a medical bill. Can they prove it? Medical billing is full of errors, and you can demand they validate the amount before you pay. Our attorneys can review it. Free case review.",
       "footer": "Attorney Advertising. Prior outcomes don't guarantee similar results. Crēdo Legal — responsible attorney Jack [CONFIRM], licensed in NY & NJ. [firm mailing address · phone · email — CONFIRM]. Includes AI-generated content. The choice of a lawyer is an important decision and should not be based solely upon advertisements."
      },
      {
       "variant": "Reassurance",
       "text": "A surprise medical bill is worth a second look before you pay. Coding errors and duplicate charges are common, and a collector has to validate the amount if you ask. Free review.",
       "footer": "Attorney Advertising. Prior outcomes don't guarantee similar results. Crēdo Legal — responsible attorney Jack [CONFIRM], licensed in NY & NJ. [firm mailing address · phone · email — CONFIRM]. Includes AI-generated content. The choice of a lawyer is an important decision and should not be based solely upon advertisements."
      }
     ],
     "creatives": [
      {
       "direction": "illustration",
       "utm_content": "medical-validation-illustration",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/medical-debt/v3-pilot/Medical_Rights_D1_Illustration_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/medical-debt/v3-pilot/Medical_Rights_D1_Illustration_1_91x1.png"
       }
      },
      {
       "direction": "photo",
       "utm_content": "medical-validation-photo",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/medical-debt/v3-pilot/Medical_Rights_D2_Photo_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/medical-debt/v3-pilot/Medical_Rights_D2_Photo_1_91x1.png"
       }
      },
      {
       "direction": "stilllife",
       "utm_content": "medical-validation-stilllife",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/medical-debt/v3-pilot/Medical_Rights_D3_StillLife_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/medical-debt/v3-pilot/Medical_Rights_D3_StillLife_1_91x1.png"
       }
      }
     ]
    },
    {
     "key": "medical-billing",
     "topic": "Surprise medical bill — errors are common",
     "headline": "Make Them Prove You Owe It",
     "cta": "Get a Free Review",
     "finalUrl": "https://start.credolegal.com/medical-debt-bills-errors",
     "finalUrlUtm": "https://start.credolegal.com/medical-debt-bills-errors?utm_source=nextdoor&utm_medium=paid_social&utm_campaign=credo_nd_traffic_v1&utm_term=medical&utm_content=medical-billing",
     "bodies": [
      {
       "variant": "Default",
       "text": "Behind on a medical bill and hearing from collectors? You can make them validate the amount in writing first, and billing errors are common. Our attorneys can review what you owe. Free case review.",
       "footer": "Attorney Advertising. Prior outcomes don't guarantee similar results. Crēdo Legal — responsible attorney Jack [CONFIRM], licensed in NY & NJ. [firm mailing address · phone · email — CONFIRM]. Includes AI-generated content. The choice of a lawyer is an important decision and should not be based solely upon advertisements."
      },
      {
       "variant": "Reassurance",
       "text": "Medical debt does not have to run your life. You can require a collector to prove the amount before you pay a cent. A free review shows your options, at no cost.",
       "footer": "Attorney Advertising. Prior outcomes don't guarantee similar results. Crēdo Legal — responsible attorney Jack [CONFIRM], licensed in NY & NJ. [firm mailing address · phone · email — CONFIRM]. Includes AI-generated content. The choice of a lawyer is an important decision and should not be based solely upon advertisements."
      }
     ],
     "creatives": [
      {
       "direction": "illustration",
       "utm_content": "medical-billing-illustration",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/medical-debt/v3-pilot/Medical_Harassment_D1_Illustration_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/medical-debt/v3-pilot/Medical_Harassment_D1_Illustration_1_91x1.png"
       }
      },
      {
       "direction": "photo",
       "utm_content": "medical-billing-photo",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/medical-debt/v3-pilot/Medical_Harassment_D2_Photo_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/medical-debt/v3-pilot/Medical_Harassment_D2_Photo_1_91x1.png"
       }
      },
      {
       "direction": "stilllife",
       "utm_content": "medical-billing-stilllife",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/medical-debt/v3-pilot/Medical_Harassment_D3_StillLife_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/medical-debt/v3-pilot/Medical_Harassment_D3_StillLife_1_91x1.png"
       }
      }
     ]
    }
   ]
  },
  {
   "key": "credit-card",
   "label": "Credit card",
   "landingPage": "https://start.credolegal.com/credit-card-debt-negotiation",
   "ads": [
    {
     "key": "creditcard-validation",
     "topic": "Old card balance — do they even own it?",
     "headline": "Make Them Prove You Owe It",
     "cta": "Get a Free Review",
     "finalUrl": "https://start.credolegal.com/credit-card-debt-negotiation",
     "finalUrlUtm": "https://start.credolegal.com/credit-card-debt-negotiation?utm_source=nextdoor&utm_medium=paid_social&utm_campaign=credo_nd_traffic_v1&utm_term=credit-card&utm_content=creditcard-validation",
     "bodies": [
      {
       "variant": "Default",
       "text": "Pressured over an old credit card balance? Debt buyers often cannot produce the contract to prove they own it, and balances get inflated with fees. You can make them validate it, and may settle for less. Free review.",
       "footer": "Attorney Advertising. Prior outcomes don't guarantee similar results. Crēdo Legal — responsible attorney Jack [CONFIRM], licensed in NY & NJ. [firm mailing address · phone · email — CONFIRM]. Includes AI-generated content. The choice of a lawyer is an important decision and should not be based solely upon advertisements."
      },
      {
       "variant": "Reassurance",
       "text": "An old card balance is not always what they claim. You can require proof they own the debt, and in many cases settle for less. A free review shows where you really stand.",
       "footer": "Attorney Advertising. Prior outcomes don't guarantee similar results. Crēdo Legal — responsible attorney Jack [CONFIRM], licensed in NY & NJ. [firm mailing address · phone · email — CONFIRM]. Includes AI-generated content. The choice of a lawyer is an important decision and should not be based solely upon advertisements."
      }
     ],
     "creatives": [
      {
       "direction": "illustration",
       "utm_content": "creditcard-validation-illustration",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/credit-card/v3-pilot/CC_Negotiation_D1_Illustration_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/credit-card/v3-pilot/CC_Negotiation_D1_Illustration_1_91x1.png"
       }
      },
      {
       "direction": "photo",
       "utm_content": "creditcard-validation-photo",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/credit-card/v3-pilot/CC_Negotiation_D2_Photo_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/credit-card/v3-pilot/CC_Negotiation_D2_Photo_1_91x1.png"
       }
      },
      {
       "direction": "stilllife",
       "utm_content": "creditcard-validation-stilllife",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/credit-card/v3-pilot/CC_Negotiation_D3_StillLife_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/credit-card/v3-pilot/CC_Negotiation_D3_StillLife_1_91x1.png"
       }
      }
     ]
    },
    {
     "key": "creditcard-collections",
     "topic": "Card collectors calling — make them validate",
     "headline": "Get a Free Review of Your Case",
     "cta": "Get a Free Review",
     "finalUrl": "https://start.credolegal.com/credit-card-debt-negotiation",
     "finalUrlUtm": "https://start.credolegal.com/credit-card-debt-negotiation?utm_source=nextdoor&utm_medium=paid_social&utm_campaign=credo_nd_traffic_v1&utm_term=credit-card&utm_content=creditcard-collections",
     "bodies": [
      {
       "variant": "Default",
       "text": "Collectors calling about a credit card debt? You can make them validate it in writing before you pay, and many cannot back up the amount they claim. Our attorneys can help. Free case review.",
       "footer": "Attorney Advertising. Prior outcomes don't guarantee similar results. Crēdo Legal — responsible attorney Jack [CONFIRM], licensed in NY & NJ. [firm mailing address · phone · email — CONFIRM]. Includes AI-generated content. The choice of a lawyer is an important decision and should not be based solely upon advertisements."
      },
      {
       "variant": "Reassurance",
       "text": "You do not have to face credit card collectors alone. Make them prove the debt is valid first, and you may owe far less than they say. Free review, no cost to you.",
       "footer": "Attorney Advertising. Prior outcomes don't guarantee similar results. Crēdo Legal — responsible attorney Jack [CONFIRM], licensed in NY & NJ. [firm mailing address · phone · email — CONFIRM]. Includes AI-generated content. The choice of a lawyer is an important decision and should not be based solely upon advertisements."
      }
     ],
     "creatives": [
      {
       "direction": "illustration",
       "utm_content": "creditcard-collections-illustration",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/credit-card/v3-pilot/CC_Harassment_D1_Illustration_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/credit-card/v3-pilot/CC_Harassment_D1_Illustration_1_91x1.png"
       }
      },
      {
       "direction": "photo",
       "utm_content": "creditcard-collections-photo",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/credit-card/v3-pilot/CC_Harassment_D2_Photo_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/credit-card/v3-pilot/CC_Harassment_D2_Photo_1_91x1.png"
       }
      },
      {
       "direction": "stilllife",
       "utm_content": "creditcard-collections-stilllife",
       "files": {
        "1x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/credit-card/v3-pilot/CC_Harassment_D3_StillLife_1x1.png",
        "1.91x1": "https://2-human.github.io/credo-public-meta-ads-preview/assets/credit-card/v3-pilot/CC_Harassment_D3_StillLife_1_91x1.png"
       }
      }
     ]
    }
   ]
  }
 ],
 "package": {
  "zip": "handoff/nextdoor/credo-nextdoor-ads-v1.zip",
  "size": "~34 MB",
  "files": 42
 },
 "metrics": {}
};
