/* Crēdo Legal — Nextdoor engagement candidates (generated by scripts/nextdoor/nd-engage.js).
 * days[YYYY-MM-DD] = {scannedAt, feedPosts, candidates:[…]} — one scan per day, 5 candidates,
 * each with a suggested reaction + comment the operator can accept, edit or skip on engagement.html.
 * Do not hand-edit; re-run the scan or use the helper. */
window.CREDO_ND_ENGAGE = {
 "days": {
  "2026-09-17": {
   "scannedAt": "2026-09-17T17:35:00.000Z",
   "feedPosts": 18,
   "todayPosts": 6,
   "excluded": [
    {
     "id": "511549196",
     "who": "Denise M.",
     "subject": "Remove Pink as a UNICEF Ambassador",
     "reason": "Political / divisive — a business page should stay out."
    }
   ],
   "candidates": [
    {
     "id": "511641073",
     "short": "Dnfnzjhnxj4q",
     "url": "https://nextdoor.com/p/Dnfnzjhnxj4q/",
     "who": "Marc Santa Maria",
     "hood": "Alphabet City",
     "t": 1789665281816,
     "age": "13 min ago",
     "subject": "PROTECT YOUR BIKES & SCOOTERS.",
     "body": "PROTECT YOUR BIKES & SCOOTERS. THIS CAN HAPPEN IN ONE MINUTE.\nMy locked up electric scooter was stolen in BROAD DAYLIGHT outside Crunch Bowery at 2 Cooper Square.\n\n📅 August 14\n⏰ ~11:15 AM\n📍 East Village, NYC\n\nI have video footage of the theft, and I'm sharing it as a public-awareness reminder because I was shocked by how quickly and casually it happened.\n\nIf you ride or park a bike, e-bike or scooter in NYC: def be extra careful about how and where you lock it. Hoping a little extra awareness goes a long way. Safe and good vibes to us all.",
     "reactions": 0,
     "comments": 0,
     "topics": [
      "Safety"
     ],
     "photo": null,
     "why": "Safety warning shared for the neighborhood's benefit — the kind of post Credo's scam-alert voice belongs next to. No comments yet, so a reply is visible.",
     "suggestReaction": "Helpful",
     "suggestComment": "Sorry this happened, and thank you for sharing the footage instead of just moving on. It is exactly the kind of heads-up that helps the next person. Hope the scooter turns up."
    },
    {
     "id": "511603461",
     "short": "CyF5_sKckpLJ",
     "url": "https://nextdoor.com/p/CyF5_sKckpLJ/",
     "who": "Alyssa Vignone",
     "hood": "Midtown SC (E32-Madison)",
     "t": 1789661582208,
     "age": "1 hr ago",
     "subject": "I need to find a new home for my cat.",
     "body": "I need to find a new home for my cat. I moved in with my boyfriend and his allergies are worse than we thought. Please let me know if you have any recommendations or leads",
     "reactions": 10,
     "comments": 14,
     "topics": [
      "Recommendations"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/32/17/32174fc0b632439cb246f3df1c7e3276.jpeg",
     "why": "Warm, active thread (10 reactions, 14 comments) from a neighbor asking for help — a kind word reads as neighborly, same tone as the Clara reply.",
     "suggestReaction": "Like",
     "suggestComment": "Hard decision to have to make. Hoping a good home turns up quickly — this thread is a great sign that neighbors are looking out."
    },
    {
     "id": "511531162",
     "short": "ZcTDT-hMJM6P",
     "url": "https://nextdoor.com/p/ZcTDT-hMJM6P/",
     "who": "Joann Smith",
     "hood": "FiDi (West-Broadway-Pearl)",
     "t": 1789642296587,
     "age": "6 hr ago",
     "subject": "Hope looks good as hell even though it's subbed…",
     "body": "Hope looks good as hell even though it's subbed but guess what today is the last day for 4DX and the only one so far watching it is me loll unbelievable that's good for me I got the hole theater.",
     "reactions": 2,
     "comments": 1,
     "topics": [
      "General"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/47/aa/47aa0ef4ba0c8eb9611552f99ddf647a.jpeg",
     "why": "Light, local FiDi post (Credo's own neighborhood) with almost no engagement — a friendly reaction is low-risk goodwill.",
     "suggestReaction": "Haha",
     "suggestComment": "A private screening in FiDi — that is the best possible outcome of a slow Wednesday."
    },
    {
     "id": "511585657",
     "short": "fc3_ZtgJw4ck",
     "url": "https://nextdoor.com/p/fc3_ZtgJw4ck/",
     "who": "Elise Weber",
     "hood": "Tribeca",
     "t": 1789657620012,
     "age": "2 hr ago",
     "subject": "We're Hiring: Procurement Manager",
     "body": "We're Hiring: Procurement Manager\n\nFamily-owned shipping business looking for a sharp, hands-on Procurement Manager to join our growing team.\nWhat you'll do:\nSource and negotiate the best rates and terms with suppliers, carriers, and service providers\n• Manage contracts, RFQs/tenders, and supplier performance\n• Monitor market trends (freight rates, capacity, costs) and identify savings opportunities\n• Build strong, reliable supplier relationships while reducing risk\n• Work closely with operations and finance to keep our supply chain running smoothly and cost-effectively\n• Ensure compliance and maintain accurate procurement records\n\nWhat we're looking for:\n• Proven experience in procurement (ideally in shipping, logistics, or freight)\n• Strong negotiation and analytical skills\n• Solid understanding of supply chain and cost management\n• Bachelor's degree in Supply Chain, Business…",
     "reactions": 1,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Local family business hiring — a supportive reaction from another downtown business is natural. Comment optional.",
     "suggestReaction": "Like",
     "suggestComment": "Good luck with the search — nice to see a family-owned downtown business growing."
    },
    {
     "id": "511602124",
     "short": "4Z9YRk8SFr4J",
     "url": "https://nextdoor.com/p/4Z9YRk8SFr4J/",
     "who": "Lora T.",
     "hood": "SoHo (Greene-Broome-Canal)",
     "t": 1789661366207,
     "age": "1 hr ago",
     "subject": "Question for bicyclists: how do you feel about fire engines responding to a fire by racing inside a two-lane protected bike lane?",
     "body": "Question for bicyclists:  how do you feel about fire engines responding to a fire by racing inside a two-lane protected bike lane?  Should they be allowed?",
     "reactions": 1,
     "comments": 25,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Busy discussion (25 comments) but it is a street-policy debate — react only, no comment, so Credo is present without taking a side.",
     "suggestReaction": "Insightful",
     "suggestComment": ""
    }
   ]
  },
  "2026-09-18": {
   "scannedAt": "2026-09-18T12:07:53.593Z",
   "feedPosts": 11,
   "todayPosts": 2,
   "excluded": [],
   "candidates": [
    {
     "id": "511812166",
     "short": "STwYq2CJHSbr",
     "url": "https://nextdoor.com/p/STwYq2CJHSbr/",
     "who": "Jasmine Von Rock",
     "hood": "Kips Bay (32nd-1st-34th-3rd)",
     "t": 1789732901634,
     "age": "5 min ago",
     "subject": "I love you, my neighbors ❤️",
     "body": "I love you, my neighbors ❤️",
     "reactions": 0,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "A simple, warm good-morning message to the neighborhood — nothing controversial, just a nice one to acknowledge.",
     "suggestReaction": "Like",
     "suggestComment": ""
    },
    {
     "id": "511812120",
     "short": "thkZHcMRZXCx",
     "url": "https://nextdoor.com/p/thkZHcMRZXCx/",
     "who": "Jasmine Von Rock",
     "hood": "Kips Bay (32nd-1st-34th-3rd)",
     "t": 1789732870864,
     "age": "6 min ago",
     "subject": "The fact that you all made it through another week is AMAZING 👏 🤩 I love you.",
     "body": "The fact that you all made it through another week is AMAZING 👏 🤩 I love you. I'm proud of you. Keep going 💪 ✨️",
     "reactions": 0,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Same neighbor's Friday-morning encouragement post, posted a minute apart from the one above — worth a reaction but keeping the comment to just the first post so it doesn't look automated.",
     "suggestReaction": "Like",
     "suggestComment": ""
    }
   ]
  }
 }
};
