/* Crēdo Legal — Nextdoor engagement candidates (generated by scripts/nextdoor/nd-engage.js).
 * days[YYYY-MM-DD] = {scannedAt, feedPosts, candidates:[…]} — one scan per day, 5 candidates,
 * each with a suggested reaction + comment the operator can accept, edit or skip on engagement.html.
 * Do not hand-edit; re-run the scan or use the helper. */
window.CREDO_ND_ENGAGE = {
 "days": {
  "2026-09-17": {
   "scannedAt": "2026-09-17T17:35:00.000Z",
   "feedPosts": 18,
   "todayPosts": 6,
   "excluded": [
    {
     "id": "511549196",
     "who": "Denise M.",
     "subject": "Remove Pink as a UNICEF Ambassador",
     "reason": "Political / divisive — a business page should stay out."
    }
   ],
   "candidates": [
    {
     "id": "511641073",
     "short": "Dnfnzjhnxj4q",
     "url": "https://nextdoor.com/p/Dnfnzjhnxj4q/",
     "who": "Marc Santa Maria",
     "hood": "Alphabet City",
     "t": 1789665281816,
     "age": "13 min ago",
     "subject": "PROTECT YOUR BIKES & SCOOTERS.",
     "body": "PROTECT YOUR BIKES & SCOOTERS. THIS CAN HAPPEN IN ONE MINUTE.\nMy locked up electric scooter was stolen in BROAD DAYLIGHT outside Crunch Bowery at 2 Cooper Square.\n\n📅 August 14\n⏰ ~11:15 AM\n📍 East Village, NYC\n\nI have video footage of the theft, and I'm sharing it as a public-awareness reminder because I was shocked by how quickly and casually it happened.\n\nIf you ride or park a bike, e-bike or scooter in NYC: def be extra careful about how and where you lock it. Hoping a little extra awareness goes a long way. Safe and good vibes to us all.",
     "reactions": 0,
     "comments": 0,
     "topics": [
      "Safety"
     ],
     "photo": null,
     "why": "Safety warning shared for the neighborhood's benefit — the kind of post Credo's scam-alert voice belongs next to. No comments yet, so a reply is visible.",
     "suggestReaction": "Helpful",
     "suggestComment": "Sorry this happened, and thank you for sharing the footage instead of just moving on. It is exactly the kind of heads-up that helps the next person. Hope the scooter turns up."
    },
    {
     "id": "511603461",
     "short": "CyF5_sKckpLJ",
     "url": "https://nextdoor.com/p/CyF5_sKckpLJ/",
     "who": "Alyssa Vignone",
     "hood": "Midtown SC (E32-Madison)",
     "t": 1789661582208,
     "age": "1 hr ago",
     "subject": "I need to find a new home for my cat.",
     "body": "I need to find a new home for my cat. I moved in with my boyfriend and his allergies are worse than we thought. Please let me know if you have any recommendations or leads",
     "reactions": 10,
     "comments": 14,
     "topics": [
      "Recommendations"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/32/17/32174fc0b632439cb246f3df1c7e3276.jpeg",
     "why": "Warm, active thread (10 reactions, 14 comments) from a neighbor asking for help — a kind word reads as neighborly, same tone as the Clara reply.",
     "suggestReaction": "Like",
     "suggestComment": "Hard decision to have to make. Hoping a good home turns up quickly — this thread is a great sign that neighbors are looking out."
    },
    {
     "id": "511531162",
     "short": "ZcTDT-hMJM6P",
     "url": "https://nextdoor.com/p/ZcTDT-hMJM6P/",
     "who": "Joann Smith",
     "hood": "FiDi (West-Broadway-Pearl)",
     "t": 1789642296587,
     "age": "6 hr ago",
     "subject": "Hope looks good as hell even though it's subbed…",
     "body": "Hope looks good as hell even though it's subbed but guess what today is the last day for 4DX and the only one so far watching it is me loll unbelievable that's good for me I got the hole theater.",
     "reactions": 2,
     "comments": 1,
     "topics": [
      "General"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/47/aa/47aa0ef4ba0c8eb9611552f99ddf647a.jpeg",
     "why": "Light, local FiDi post (Credo's own neighborhood) with almost no engagement — a friendly reaction is low-risk goodwill.",
     "suggestReaction": "Haha",
     "suggestComment": "A private screening in FiDi — that is the best possible outcome of a slow Wednesday."
    },
    {
     "id": "511585657",
     "short": "fc3_ZtgJw4ck",
     "url": "https://nextdoor.com/p/fc3_ZtgJw4ck/",
     "who": "Elise Weber",
     "hood": "Tribeca",
     "t": 1789657620012,
     "age": "2 hr ago",
     "subject": "We're Hiring: Procurement Manager",
     "body": "We're Hiring: Procurement Manager\n\nFamily-owned shipping business looking for a sharp, hands-on Procurement Manager to join our growing team.\nWhat you'll do:\nSource and negotiate the best rates and terms with suppliers, carriers, and service providers\n• Manage contracts, RFQs/tenders, and supplier performance\n• Monitor market trends (freight rates, capacity, costs) and identify savings opportunities\n• Build strong, reliable supplier relationships while reducing risk\n• Work closely with operations and finance to keep our supply chain running smoothly and cost-effectively\n• Ensure compliance and maintain accurate procurement records\n\nWhat we're looking for:\n• Proven experience in procurement (ideally in shipping, logistics, or freight)\n• Strong negotiation and analytical skills\n• Solid understanding of supply chain and cost management\n• Bachelor's degree in Supply Chain, Business…",
     "reactions": 1,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Local family business hiring — a supportive reaction from another downtown business is natural. Comment optional.",
     "suggestReaction": "Like",
     "suggestComment": "Good luck with the search — nice to see a family-owned downtown business growing."
    },
    {
     "id": "511602124",
     "short": "4Z9YRk8SFr4J",
     "url": "https://nextdoor.com/p/4Z9YRk8SFr4J/",
     "who": "Lora T.",
     "hood": "SoHo (Greene-Broome-Canal)",
     "t": 1789661366207,
     "age": "1 hr ago",
     "subject": "Question for bicyclists: how do you feel about fire engines responding to a fire by racing inside a two-lane protected bike lane?",
     "body": "Question for bicyclists:  how do you feel about fire engines responding to a fire by racing inside a two-lane protected bike lane?  Should they be allowed?",
     "reactions": 1,
     "comments": 25,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Busy discussion (25 comments) but it is a street-policy debate — react only, no comment, so Credo is present without taking a side.",
     "suggestReaction": "Insightful",
     "suggestComment": ""
    }
   ]
  },
  "2026-09-18": {
   "scannedAt": "2026-09-18T12:07:53.593Z",
   "feedPosts": 11,
   "todayPosts": 2,
   "excluded": [],
   "candidates": [
    {
     "id": "511812166",
     "short": "STwYq2CJHSbr",
     "url": "https://nextdoor.com/p/STwYq2CJHSbr/",
     "who": "Jasmine Von Rock",
     "hood": "Kips Bay (32nd-1st-34th-3rd)",
     "t": 1789732901634,
     "age": "5 min ago",
     "subject": "I love you, my neighbors ❤️",
     "body": "I love you, my neighbors ❤️",
     "reactions": 0,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "A simple, warm good-morning message to the neighborhood — nothing controversial, just a nice one to acknowledge.",
     "suggestReaction": "Like",
     "suggestComment": ""
    },
    {
     "id": "511812120",
     "short": "thkZHcMRZXCx",
     "url": "https://nextdoor.com/p/thkZHcMRZXCx/",
     "who": "Jasmine Von Rock",
     "hood": "Kips Bay (32nd-1st-34th-3rd)",
     "t": 1789732870864,
     "age": "6 min ago",
     "subject": "The fact that you all made it through another week is AMAZING 👏 🤩 I love you.",
     "body": "The fact that you all made it through another week is AMAZING 👏 🤩 I love you. I'm proud of you. Keep going 💪 ✨️",
     "reactions": 0,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Same neighbor's Friday-morning encouragement post, posted a minute apart from the one above — worth a reaction but keeping the comment to just the first post so it doesn't look automated.",
     "suggestReaction": "Like",
     "suggestComment": ""
    }
   ]
  },
  "2026-09-19": {
   "scannedAt": "2026-09-21T07:11:40.000Z",
   "feedPosts": 19,
   "todayPosts": 7,
   "excluded": [
    {
     "id": "512194492",
     "who": "David Goldstein",
     "subject": "Rally set Sunday, 9/20 at noon to help save the AMC Kips Bay 15",
     "reason": "Organised rally with elected officials — civic advocacy, outside the neutral neighbourly lane."
    },
    {
     "id": "512220027",
     "who": "Beth Harkavy",
     "subject": "Any non-profits or political offices need an experienced person",
     "reason": "Explicitly political work — excluded as political."
    },
    {
     "id": "512190265",
     "who": "Francesca Espinal",
     "subject": "Interested in building connections.",
     "reason": "Invites strangers to phone calls — a business page engaging could read as endorsement of a risky ask."
    },
    {
     "id": "512059186",
     "who": "Joann Smith",
     "subject": "Hope was definitely good and exciting to watch the killing was horrifically bloody",
     "reason": "Film talk, but the wording reads graphically violent out of context — wrong tone for a law firm to amplify."
    }
   ],
   "candidates": [
    {
     "id": "512209429",
     "short": "TLs-Br5WrbJg",
     "url": "https://nextdoor.com/p/TLs-Br5WrbJg/",
     "who": "Ivan Eone",
     "hood": "Chelsea (23rd-10th-34th)",
     "t": 1789869068609,
     "age": "1 day ago",
     "subject": "Watch out, neighbors.",
     "body": "Watch out, neighbors. There are some incredibly reckless riders speeding around the neighborhood completely unchecked. I was almost hit today along with a few others. Please stay safe and keep your eyes peeled!",
     "reactions": 19,
     "comments": 11,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "A straightforward street-safety warning with real traction (19 reactions, 11 comments) — the top-priority category, and nobody is named or blamed.",
     "suggestReaction": "Helpful",
     "suggestComment": "Thank you for flagging this, and glad you are okay. A heads-up like this is what makes people look twice at the crossings."
    },
    {
     "id": "512193641",
     "short": "9tZMDMkTmKXc",
     "url": "https://nextdoor.com/p/9tZMDMkTmKXc/",
     "who": "Josselyn Magaly Buna",
     "hood": "Battery Park City (River Terr)",
     "t": 1789862417690,
     "age": "1 day ago",
     "subject": "Hello neighbors, I hope you're having a wonderful weekend!",
     "body": "Hello neighbors, I hope you're having a wonderful weekend! A while ago I shared a picture of Lucky when he was a little boy. Look how much he's grown! Now Lucky has a new little brother and has become quite the protector.",
     "reactions": 293,
     "comments": 45,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "The most-loved post of the day by a wide margin (293 reactions) — a dog growing up, warm and entirely uncontroversial.",
     "suggestReaction": "Like",
     "suggestComment": "Lucky has grown up well, and a big brother now too. Updates like this are the best part of the feed."
    },
    {
     "id": "512097198",
     "short": "yTmM4YS7QQMm",
     "url": "https://nextdoor.com/p/yTmM4YS7QQMm/",
     "who": "Brandon Sage",
     "hood": "Chelsea (8Ave-25th)",
     "t": 1789833459805,
     "age": "1 day ago",
     "subject": "Can anyone recommend a card shop in Manhattan that has an offering of more uniquely funny cards?",
     "body": "Can anyone recommend a card shop in Manhattan that has an offering of more uniquely funny cards? There used to be a couple on the upper west side and they're both closed. I've been to Barnes & Noble and I've been to so many others, but I can't find a store which offers offbeat, funny greeting cards. Can anyone help me with this?",
     "reactions": 15,
     "comments": 63,
     "topics": [
      "Recommendations"
     ],
     "photo": null,
     "why": "A busy, friendly recommendation thread (63 comments) about small shops closing — easy to join as a neighbour without steering anyone.",
     "suggestReaction": "Like",
     "suggestComment": "Following this one. The offbeat card shops have really thinned out downtown, so hoping someone turns up a good spot."
    }
   ]
  },
  "2026-09-20": {
   "scannedAt": "2026-09-21T07:11:40.000Z",
   "feedPosts": 19,
   "todayPosts": 11,
   "excluded": [
    {
     "id": "512405585",
     "who": "Keith O. Bennett",
     "subject": "I'M GIVING A LITTLE GIFT TO THE FIRST 5 PEOPLE WHO DM ME THE WORD \"GOD IS GOOD\"",
     "reason": "Religious framing plus a DM-bait giveaway pattern — excluded as religious and likely a scam hook."
    },
    {
     "id": "512405560",
     "who": "Keith O. Bennett",
     "subject": "I'M GIVING A LITTLE GIFT TO THE FIRST 5 PEOPLE WHO DM ME THE WORD \"GOD IS GOOD\"",
     "reason": "Duplicate of the post above, same reason."
    },
    {
     "id": "512402236",
     "who": "Grace Prego",
     "subject": "AFFORDABLE HOUSE FOR RENT!!!",
     "reason": "Rental listing posted twice within an hour — promotional, and the duplication pattern reads as spam."
    },
    {
     "id": "512396164",
     "who": "Grace Prego",
     "subject": "AFFORDABLE HOUSE FOR RENT",
     "reason": "Duplicate of the listing above, same reason."
    },
    {
     "id": "512309075",
     "who": "Vee P.",
     "subject": "…..hmm",
     "reason": "89 comments on a cryptic image post — cannot verify the subject, and that much heat suggests an argument."
    },
    {
     "id": "512288512",
     "who": "Elise Weber",
     "subject": "We're Hiring: Procurement Manager",
     "reason": "Corporate recruitment post rather than a neighbour's own post."
    }
   ],
   "candidates": [
    {
     "id": "512291055",
     "short": "yGC67sh2BmGR",
     "url": "https://nextdoor.com/p/yGC67sh2BmGR/",
     "who": "Ashley Alsaiedi",
     "hood": "Chelsea (23rd-10th-34th)",
     "t": 1789922647881,
     "age": "14 hr ago",
     "subject": "finch loose near 14 haratio st",
     "body": "finch loose near 14 haratio st",
     "reactions": 3,
     "comments": 2,
     "topics": [
      "Lost & Found"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/af/65/af65238df9d09cfea8d28387e8a7f5d8.jpeg",
     "why": "A lost pet with a photo — the classic neighbourly request, and the kind of post where a kind word costs nothing.",
     "suggestReaction": "Helpful",
     "suggestComment": "Hope the little one is back home safe by now. Good of you to post the photo so neighbors know what to look for."
    },
    {
     "id": "512402371",
     "short": "Mjq9jnnnLdrM",
     "url": "https://nextdoor.com/p/Mjq9jnnnLdrM/",
     "who": "Joseph DiMartino",
     "hood": "Brooklyn Heights",
     "t": 1789960023131,
     "age": "3 hr ago",
     "subject": "Twilight",
     "body": "Twilight",
     "reactions": 3,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/15/48/15488d4ab79f118cf87fb5a1bf986e65.jpeg",
     "why": "A one-word photo post of the evening sky — pure local appreciation, no angle to get wrong.",
     "suggestReaction": "Like",
     "suggestComment": "Beautiful shot. The light over the city this time of year is hard to beat."
    },
    {
     "id": "512244374",
     "short": "5WKjF7Nh43wK",
     "url": "https://nextdoor.com/p/5WKjF7Nh43wK/",
     "who": "Joann Smith",
     "hood": "FiDi (West-Broadway-Pearl)",
     "t": 1789905842454,
     "age": "19 hr ago",
     "subject": "Ok yesterday was a good day I went to church lunch and then I went to movies to see Resident Evil in 4DX",
     "body": "Ok yesterday was a good day I went to church lunch and then I went to movies to see Resident Evil in 4DX and because of the special effects I was jumping and screaming out loud and that chair caused it all loll and god damn and it's a continuation for another movie yet to come, but it was definitely funny and scary at the same time just like Hope, your gotta experience 4DX style at least once in your life loll it's always with a action movie.",
     "reactions": 2,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/c0/76/c0760ab3b450e53bc08d601651c16f1a.jpeg",
     "why": "Cheerful account of a day out — light local chatter with no one to offend, and it has had no replies yet.",
     "suggestReaction": "Haha",
     "suggestComment": "4DX really does get you — the chair is half the movie. Sounds like a great day out."
    },
    {
     "id": "512324948",
     "short": "xn5mMNcnt2DG",
     "url": "https://nextdoor.com/p/xn5mMNcnt2DG/",
     "who": "Julieanne Goris",
     "hood": "Ft Greene (Ingersoll-Whitman)",
     "t": 1789932413585,
     "age": "11 hr ago",
     "subject": "Hi everyone!",
     "body": "Hi everyone! I am offering chess lessons for complete beginners in and around the Fort Greene area. I have a lot of experience coaching kids between 5 and 7 years old, getting them tournament-ready, and helping promote confidence & precision. Rates Flexible",
     "reactions": 2,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "A neighbour starting something small and local for kids — warm to encourage, and no competitive overlap with Credo.",
     "suggestReaction": "Like",
     "suggestComment": "Chess at that age is such a good confidence builder. Hope you get a full roster of local kids."
    },
    {
     "id": "512371119",
     "short": "Y7yGjPHnBKMg",
     "url": "https://nextdoor.com/p/Y7yGjPHnBKMg/",
     "who": "Linda Montoya",
     "hood": "Stuyvesant Hts (Park-Myrtle)",
     "t": 1789947205951,
     "age": "7 hr ago",
     "subject": "I'm on Rover.",
     "body": "I'm on Rover. Anyone need a dog sitter I'm your girl. Linda M.",
     "reactions": 2,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "A neighbour offering a small service with no replies yet — a friendly acknowledgement, stopping short of vouching for her.",
     "suggestReaction": "Like",
     "suggestComment": "Good luck with it. Neighbors are always looking for someone nearby for the dogs."
    }
   ]
  },
  "2026-09-21": {
   "scannedAt": "2026-09-21T07:34:00.501Z",
   "feedPosts": 20,
   "todayPosts": 1,
   "excluded": [],
   "candidates": [
    {
     "id": "512416677",
     "short": "gww_t5pn6Ps-",
     "url": "https://nextdoor.com/p/gww_t5pn6Ps-/",
     "who": "Paris Pakeera",
     "hood": "E Williamsburg (Morgan-Divisn)",
     "t": 1789972067236,
     "age": "1 hr ago",
     "subject": "Would anyone like to share paranormal experiences?",
     "body": "Would anyone like to share paranormal experiences?",
     "reactions": 1,
     "comments": 1,
     "topics": [
      "Recommendations"
     ],
     "photo": null,
     "why": "Light, harmless local curiosity post with zero controversy risk — good low-key engagement.",
     "suggestReaction": "Wow",
     "suggestComment": "Ha, now you have me curious — following this one to see what stories people share!"
    }
   ]
  },
  "2026-09-22": {
   "scannedAt": "2026-09-22T07:07:15.895Z",
   "feedPosts": 17,
   "todayPosts": 3,
   "excluded": [
    {
     "id": "512662840",
     "who": "Takima Darnell",
     "subject": "SUNDAY",
     "reason": "Body is just \"SUNDAY / Join Me\" with a photo we can't inspect for context — too ambiguous to safely engage (could be a church/event invite)."
    },
    {
     "id": "512662826",
     "who": "Takima Darnell",
     "subject": "",
     "reason": "Empty subject/body, same author and same minute as the SUNDAY post — almost certainly a second photo card from the same album post, no standalone content."
    }
   ],
   "candidates": [
    {
     "id": "512650344",
     "short": "-43P8htQgYB8",
     "url": "https://nextdoor.com/p/-43P8htQgYB8/",
     "who": "Natalia Ahmed",
     "hood": "Greenwich Village (3-10-Bway-Uni)",
     "t": 1790051801903,
     "age": "2 hr ago",
     "subject": "Hi everyone, I’m a new college student in New York and if anyone is in the need of affordable dog walking please feel free to reach out.",
     "body": "Hi everyone, I’m a new college student in New York and if anyone is in the need of affordable dog walking please feel free to reach out. I love dogs and have one myself and have done pet sitting back at home so I would take great care of your pets 💗",
     "reactions": 1,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "New college student in the neighborhood offering affordable dog-walking and pet-sitting — a warm, low-risk neighborly post that's easy to welcome and support.",
     "suggestReaction": "Helpful",
     "suggestComment": "Welcome to the neighborhood! What a lovely thing to offer — hope it helps you meet some furry (and two-legged) neighbors."
    }
   ]
  },
  "2026-09-23": {
   "scannedAt": "2026-09-23T12:52:02Z",
   "feedPosts": 16,
   "todayPosts": 5,
   "excluded": [
    {
     "id": "512935510",
     "who": "Joshua Knight",
     "subject": "i am busy upgrading every single area of my life",
     "reason": "vague low-content personal post, no neighborly substance to react to"
    },
    {
     "id": "512933024",
     "who": "Heaven Perez",
     "subject": "My dog was stolen from an unlicensed rescue and was illegally given away by a group in the Bronx called new friends rescue.",
     "reason": "dispute naming a specific rescue organization, emotionally charged accusation — excluded per policy against disputes naming people/orgs"
    }
   ],
   "candidates": [
    {
     "id": "512947100",
     "short": "8CDMmHbS-sch",
     "url": "https://nextdoor.com/p/8CDMmHbS-sch/",
     "who": "Adlin A.",
     "hood": "Murray Hill (E42-Park-E38-2nd)",
     "t": 1790162765596,
     "age": "1 hr ago",
     "subject": "These two kittens need a foster home!",
     "body": "These two kittens need a foster home!\n\nThey were surrendered to our rescue by someone who had been hoarding cats. Some of their siblings are already safe with a foster, but these two are still waiting for a place to land.\n\nThey need a safe, loving home where they can be cared for while we find their forever families. If you can foster these two kittens, please message us. \n\nPlease share to help them find their foster! \n\nLucky Cat Rescue \nNonprofit",
     "reactions": 3,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": "https://d16kzk4negkp9h.cloudfront.net/e5/fa/15/e5fa15958123bdc8a746e3e022e946d6/transcoded-compressed-F80A7F48-6AA4-4377-A213-09E3D26D82C8.mp4",
     "why": "Neighborly rescue/foster request — warm, positive, no controversy.",
     "suggestReaction": "Helpful",
     "suggestComment": "Hope these two sweet kittens find a loving foster soon, thank you for taking them in and looking out for them."
    },
    {
     "id": "512933414",
     "short": "Z4wdbN57RRZY",
     "url": "https://nextdoor.com/p/Z4wdbN57RRZY/",
     "who": "Jessica Sander",
     "hood": "Bedford Stuyvesant (Bd-Lfyt)",
     "t": 1790146126416,
     "age": "6 hr ago",
     "subject": "Found dog!!",
     "body": "Found dog!! \n\nI found a dog running around the border of Bed-Stuy and Clinton Hill. He’s an adult male, white with a few brown patches, possibly a bully mix, no collar. If you lost your dog, please contact me.\n\nI will require proof of ownership before I return him. If I can’t find his owner soon, I will be contacting some rescues I work with.",
     "reactions": 5,
     "comments": 0,
     "topics": [
      "Lost & Found"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/33/52/3352ef916c87f2ea637c99bf6c02c13a.jpeg",
     "why": "Lost & found neighborly post, low-conflict, easy to engage warmly.",
     "suggestReaction": "Helpful",
     "suggestComment": "So relieved he found someone kind to look after him, hope his owner turns up soon!"
    },
    {
     "id": "512921718",
     "short": "Jb-f3h-_BWqc",
     "url": "https://nextdoor.com/p/Jb-f3h-_BWqc/",
     "who": "Maki Sawyer",
     "hood": "FiDi (Wall-Broad)",
     "t": 1790136051423,
     "age": "8 hr ago",
     "subject": "Hello, I live in a small building in the Financial District with no doorman.",
     "body": "Hello, I live in a small building in the Financial District with no doorman. Yesterday, an Amazon delivery man wearing full Amazon gear stole the contents of a FedEx envelope addressed to me. The entire incident was captured on our security camera.\nAfter delivering an Amazon package to my neighbor, he reached for my FedEx envelope, ripped it open, took the items inside, and left the torn envelope behind. He even looks toward the camera before turning away and taking the contents. \nMy super reported the incident to the NYPD, but as far as I know, he is still delivering Amazon packages in the neighborhood. I’m concerned this may not be the first time and that he’ll do it again.\nI contacted Amazon, but was told they couldn’t take action unless the NYPD contacted them. It’s shocking and upsetting, and I want my neighbors to be aware and to keep an eye on their packages.",
     "reactions": 4,
     "comments": 1,
     "topics": [
      "Safety"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/32/0d/320d383f5203b316554503667799ec45.png",
     "why": "Package-theft safety warning with camera evidence — no named individual dispute, high community value.",
     "suggestReaction": "Helpful",
     "suggestComment": "Sorry this happened, and thank you for sharing the footage instead of just letting it go, this kind of heads-up helps the whole block stay alert."
    }
   ]
  },
  "2026-09-24": {
   "scannedAt": "2026-09-25T09:48:16Z",
   "backfill": true,
   "feedPosts": 10,
   "todayPosts": 7,
   "excluded": [
    {
     "id": "513411748",
     "who": "Eugene Solfanelli",
     "subject": "Sweetie needs help ny Essex st...",
     "reason": "unclear one-line plea (possible animal emergency) with no context or engagement, nothing safe to respond to"
    },
    {
     "id": "513377385",
     "who": "Leo King",
     "subject": "@all We are expecting to grow significantly very soon.",
     "reason": "job-recruiting solicitation for a business, not a neighbourly post"
    }
   ],
   "candidates": [
    {
     "id": "513188089",
     "short": "68wh6q-TG7Ws",
     "url": "https://nextdoor.com/p/68wh6q-TG7Ws/",
     "who": "Britt Mc",
     "hood": "Carroll Gardens",
     "t": 1790232482534,
     "age": "1 day ago",
     "subject": "Hi there.",
     "body": "Hi there. If anyone is missing a black cat (no chipped ear) there has been one in my area the past several days. Came out of nowhere. My cat doesn’t like him! He seems sweet. President & Court Street. Message me.",
     "reactions": 13,
     "comments": 2,
     "topics": [
      "Lost & Found"
     ],
     "photo": "https://d16kzk4negkp9h.cloudfront.net/61/f4/3a/61f43a5b5e265f427b4ececb0663286f/transcoded-compressed-1D2FE6D0-1823-4B3E-B9DD-1C62FE5A46CB.mp4",
     "why": "Found-pet heads-up with good traction; a kind, low-risk neighbourly thread.",
     "suggestReaction": "Helpful",
     "suggestComment": "So kind of you to keep an eye on him and post this. Hope his family around President and Court sees it soon."
    },
    {
     "id": "513430610",
     "short": "fpwXSYhXQy-c",
     "url": "https://nextdoor.com/p/fpwXSYhXQy-c/",
     "who": "James Ou",
     "hood": "Battery Park City (Albany-1Pl)",
     "t": 1790299956541,
     "age": "8 hr ago",
     "subject": "The sunset over the Hudson was insane tonight.",
     "body": "The sunset over the Hudson was insane tonight.",
     "reactions": 105,
     "comments": 16,
     "topics": [
      "General"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/e7/64/e7648dca19fff271816ab208efe2e12b.jpeg",
     "why": "The day's most lively post (105 reactions, 16 comments), pure local appreciation.",
     "suggestReaction": "Wow",
     "suggestComment": "What a shot. Evenings like this are a good reminder of why we love living by the water."
    },
    {
     "id": "513449495",
     "short": "kS9-t7mhMkP7",
     "url": "https://nextdoor.com/p/kS9-t7mhMkP7/",
     "who": "Natacha Harley",
     "hood": "FiDi (West-Broadway-Pearl)",
     "t": 1790307467843,
     "age": "6 hr ago",
     "subject": "Hi, I’m Looking for a reliable home sitter who loves pets.",
     "body": "Hi, I’m Looking for a reliable home sitter who loves pets.",
     "reactions": 2,
     "comments": 2,
     "topics": [
      "Recommendations"
     ],
     "photo": null,
     "why": "Simple neighbourly recommendation request, easy to support without taking sides.",
     "suggestReaction": "Like",
     "suggestComment": "Hope you find someone great. A sitter your pets already feel at home with makes all the difference."
    },
    {
     "id": "513412419",
     "short": "YB-SFWw3ZW-F",
     "url": "https://nextdoor.com/p/YB-SFWw3ZW-F/",
     "who": "Princess McILwain",
     "hood": "E Williamsburg (Mntrse-Leonrd)",
     "t": 1790294037677,
     "age": "9 hr ago",
     "subject": "Searching for a forever home for my sweet Lovie girl .",
     "body": "Searching for a forever home for my sweet Lovie girl . Serious inquiries only .must be active and love outdoor life . Catahoula leopard dog / German Shepherd",
     "reactions": 2,
     "comments": 1,
     "topics": [
      "Lost & Found"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/fa/1a/fa1af72595537fa1f47a28a513bcab9a.jpeg",
     "why": "Rehoming request that benefits from a boost; warm and uncontroversial.",
     "suggestReaction": "Like",
     "suggestComment": "Lovie looks like a sweetheart. Sharing good vibes that the right active family finds her soon."
    },
    {
     "id": "513273913",
     "short": "-jJxwNNgdr_-",
     "url": "https://nextdoor.com/p/-jJxwNNgdr_-/",
     "who": "Gemma Preston",
     "hood": "Tribeca",
     "t": 1790266003195,
     "age": "17 hr ago",
     "subject": "Hello,",
     "body": "Hello, \nI’m looking for a magician for a children’s birthday party. Can anyone recommend someone they’ve used or know of please?",
     "reactions": 1,
     "comments": 1,
     "topics": [
      "Recommendations"
     ],
     "photo": null,
     "why": "Light, happy neighbourly request about a kid's party.",
     "suggestReaction": "Like",
     "suggestComment": "What a fun idea for a birthday. Hope a neighbour has a great magician to recommend and the party is a hit."
    }
   ]
  },
  "2026-09-25": {
   "scannedAt": "2026-09-26T13:55:17Z",
   "backfill": true,
   "feedPosts": 9,
   "todayPosts": 3,
   "excluded": [],
   "candidates": [
    {
     "id": "513653890",
     "short": "QPYnSXqWcyf6",
     "url": "https://nextdoor.com/p/QPYnSXqWcyf6/",
     "who": "YT YT",
     "hood": "Battery Park City (Albany-1Pl)",
     "t": 1790380584065,
     "age": "12 hr ago",
     "subject": "Found near Stuyvesant HS.",
     "body": "Found near Stuyvesant HS. Smart glasses. Please identify make, color, approximate time and location.",
     "reactions": 1,
     "comments": 0,
     "topics": [
      "Lost & Found"
     ],
     "photo": null,
     "why": "Found-item post near Stuyvesant HS; classic neighbourly lost-and-found worth a boost.",
     "suggestReaction": "Helpful",
     "suggestComment": "Thank you for holding onto these and asking for details before handing them back. Smart glasses are not cheap, so someone will be very relieved."
    },
    {
     "id": "513629076",
     "short": "X-X3dbQq5fxK",
     "url": "https://nextdoor.com/p/X-X3dbQq5fxK/",
     "who": "Amyraa Elaine",
     "hood": "Park Slope (StMarks-5th)",
     "t": 1790373560928,
     "age": "14 hr ago",
     "subject": "ANY EMPLOYMENT OPPORTUNITIES?",
     "body": "ANY EMPLOYMENT OPPORTUNITIES?\nAnything off the books? \n\nI currently live in Brooklyn (park slope)\n\nI am a graphic designer, I make flyers, logos, and I also have 8+ years in customer service and call center experience. \n\nI am also a security guard and currently possess a F02/F03/F04 and security guard license",
     "reactions": 4,
     "comments": 5,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Neighbour looking for work (cost-of-living/money theme) with an active, friendly thread; encouragement fits without offering anything.",
     "suggestReaction": "Like",
     "suggestComment": "Design skills plus years of customer service and a security license is a strong mix. Wishing you luck, and hope a neighbour here has something that fits."
    },
    {
     "id": "513547719",
     "short": "FQTmxzZWj-SD",
     "url": "https://nextdoor.com/p/FQTmxzZWj-SD/",
     "who": "Keith Steier",
     "hood": "Chelsea (W29-6th-W22-7th)",
     "t": 1790354214637,
     "age": "19 hr ago",
     "subject": "Why are there so many requests for animals finding a home?",
     "body": "Why are there so many requests for animals finding a home? It just seems that pet owners get fed up or realize they can't continue providing a home. It is so unfair to the pet to now have to find a new family.",
     "reactions": 18,
     "comments": 10,
     "topics": [
      "Lost & Found"
     ],
     "photo": null,
     "why": "Most active thread of the day on pet rehoming, but opinionated and likely to draw debate — react-only.",
     "suggestReaction": "Insightful",
     "suggestComment": ""
    }
   ]
  },
  "2026-09-26": {
   "scannedAt": "2026-09-26T13:55:17Z",
   "feedPosts": 9,
   "todayPosts": 3,
   "excluded": [
    {
     "id": "513716956",
     "who": "Lagui Milagros",
     "subject": "Kylie’s Era",
     "reason": "Memorial/grief post for a pet that has died — excluded under deaths rule"
    },
    {
     "id": "513714838",
     "who": "Lagui Milagros",
     "subject": "I’ll love ❤️ her my entire existence—",
     "reason": "Same author's second memorial post for the pet — grief/death, excluded"
    }
   ],
   "candidates": [
    {
     "id": "513688917",
     "short": "zYHBJmZH9YRr",
     "url": "https://nextdoor.com/p/zYHBJmZH9YRr/",
     "who": "Frank Sp",
     "hood": "Battery Park City (River Terr)",
     "t": 1790395219631,
     "age": "8 hr ago",
     "subject": "We have a box of fancy feast cat food (30 mixed cans) , that have expiration dates of 9/2025-11/2025.",
     "body": "We have a box of fancy feast cat food (30 mixed cans) , that have expiration dates of 9/2025-11/2025. Does anyone know if these should be composted or are there rescues/shelters that can still use them? Thanks.",
     "reactions": 0,
     "comments": 1,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Neighbourly give-away question about donating unused cat food; friendly, zero-risk thread that could use a little encouragement.",
     "suggestReaction": "Like",
     "suggestComment": "Love that you're looking for a home for these instead of just tossing them. Hope a local rescue can put them to good use."
    }
   ]
  },
  "2026-09-27": {
   "scannedAt": "2026-09-28T12:19:08Z",
   "backfill": true,
   "feedPosts": 10,
   "todayPosts": 2,
   "excluded": [
    {
     "id": "514003440",
     "who": "Robert EK",
     "subject": "(photo only, no text)",
     "reason": "Photo-only post with no text; content could not be verified from the feed, so skipped rather than reacting blind"
    }
   ],
   "candidates": [
    {
     "id": "514013613",
     "short": "mC2WfHsnb96Z",
     "url": "https://nextdoor.com/p/mC2WfHsnb96Z/",
     "who": "Emily song",
     "hood": "FiDi (Wall-Broad)",
     "t": 1790543864512,
     "age": "15 hr ago",
     "subject": "Hi, I’m looking for a 24/7 monthly parking space starting in January 2027 around Quentin Rd & E 18th Street in Brooklyn (within a 10 min walk).",
     "body": "Hi, I’m looking for a 24/7 monthly parking space starting in January 2027 around Quentin Rd & E 18th Street in Brooklyn (within a 10 min walk). \nPrivate house driveways, garages, or reserved spots are all welcome! If you’re a local homeowner with an extra driveway spot or space to rent out starting early next year, please send me a message with the price and details. Thank you!",
     "reactions": 0,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Neighbourly request (looking for a parking spot) with no replies yet; a friendly nudge can help it get seen.",
     "suggestReaction": "Like",
     "suggestComment": "Planning this far ahead is smart, since good monthly spots go fast. Hope a neighbour with a spare driveway sees this and reaches out."
    }
   ]
  },
  "2026-09-28": {
   "scannedAt": "2026-09-28T12:19:08Z",
   "feedPosts": 10,
   "todayPosts": 2,
   "excluded": [
    {
     "id": "514102881",
     "who": "Cristina Fontanelli",
     "subject": "I will be there and am testifying in favor if PRISCILLA's Law!",
     "reason": "Political/legislative advocacy tied to a fatal crash (death), so excluded under the political and deaths rules"
    }
   ],
   "candidates": [
    {
     "id": "514098345",
     "short": "sksNZ5ZfXQgN",
     "url": "https://nextdoor.com/p/sksNZ5ZfXQgN/",
     "who": "Amadou Diop",
     "hood": "Alphabet City",
     "t": 1790595809705,
     "age": "35 min ago",
     "subject": "🐕 Local dog walker available in Manhattan NYC!",
     "body": "🐕 Local dog walker available in Manhattan NYC!\n\nBusy day at work? Need a midday break for your pup? I'd love to help.\n\n✅ 30 or 60 minute walks\n✅ Photo updates after every walk\n✅ Free meet-and-greet before we start\n✅ Flexible scheduling, including weekends\n\nRates start at $20 per 30 minutes & $25 for 1 hour walk. I'm currently taking on new clients, so message me if you'd like to book a spot!",
     "reactions": 0,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "The only other qualifying post today: a neighbour starting a small dog-walking side business. It's light and positive, so react-only to avoid looking like an endorsement.",
     "suggestReaction": "Like",
     "suggestComment": ""
    }
   ]
  },
  "2026-09-29": {
   "scannedAt": "2026-09-29T21:09:40.756Z",
   "feedPosts": 10,
   "todayPosts": 7,
   "excluded": [
    {
     "id": "514522334",
     "who": "Mia Jones",
     "subject": "I simply posted a message to celebrate my birthday.",
     "reason": "Interpersonal dispute / complaint about another neighbour"
    },
    {
     "id": "514521562",
     "who": "Mark Salamon",
     "subject": "Around town, everyone seems to have a store they trust more than others.",
     "reason": "Paid-survey spam with shortened link (likely scam); do not amplify"
    },
    {
     "id": "514512959",
     "who": "Anna Boyiazis",
     "subject": "Around town, everyone seems to have a store they trust more than others.",
     "reason": "Duplicate paid-survey spam with shortened link (likely scam); do not amplify"
    }
   ],
   "candidates": [
    {
     "id": "514474055",
     "short": "3wLBDQr55x7y",
     "url": "https://nextdoor.com/p/3wLBDQr55x7y/",
     "who": "Maria Maldonado",
     "hood": "Cobble Hill",
     "t": 1790704349990,
     "age": "3 hr ago",
     "subject": "Good afternoon everyone here is a picture of my baby.",
     "body": "Good afternoon everyone here is a picture of my baby. Her name is Chulita I’m sure some of you have seen her before. Well yesterday, my baby had16 teeth removed cost me a pretty penny however, during the extractions, the teeth broke off and the root is still within her gums, which means I have to take her to a specialist, surgeon, and I’m trying to find out if anyone knows of organizations that can issue grants. The worst is that this has to be done within one month I can’t wait any longer. They said a month is the top amount of time I can wait from yesterday, which was when she had the extractions any information that can be given to me. I’d greatly appreciate it.",
     "reactions": 1,
     "comments": 1,
     "topics": [
      "Recommendations"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/51/1f/511f5b27503814353434e61867399337.jpeg",
     "why": "Money and cost-of-living pressure (surprise vet bill) paired with a neighbourly request for help finding grants.",
     "suggestReaction": "Sad",
     "suggestComment": "Chulita is lucky to have someone fighting this hard for her. I hope a neighbour knows a good pet-care grant group, and sending her a quick, easy recovery."
    },
    {
     "id": "514462125",
     "short": "CYSy6_jPYq5d",
     "url": "https://nextdoor.com/p/CYSy6_jPYq5d/",
     "who": "Sunny Bright",
     "hood": "Chelsea (8Ave-25th)",
     "t": 1790701829698,
     "age": "3 hr ago",
     "subject": "Do you any of you guys know of any job oppertunities for customer service over the phone, dishwasher, customer service representative,  stock, mailroom position,  file clerk, etc.",
     "body": "Do you any of you guys know of any job oppertunities for customer service over the phone, dishwasher, customer service representative,  stock, mailroom position,  file clerk, etc. ? I work in retail right now but looking for fulltime or another part time at this time. Thank you for any help.",
     "reactions": 0,
     "comments": 0,
     "topics": [
      "Recommendations"
     ],
     "photo": null,
     "why": "Cost-of-living / income request from a neighbour looking for more work, with no replies yet.",
     "suggestReaction": "Like",
     "suggestComment": "Good for you for putting the word out. Plenty of local shops and offices hire through word of mouth, so I hope a neighbour here has a lead for you soon."
    },
    {
     "id": "514480273",
     "short": "h8qfS8D5rN7F",
     "url": "https://nextdoor.com/p/h8qfS8D5rN7F/",
     "who": "Rachel Cohn",
     "hood": "Ft Greene (Hanson-Fulton)",
     "t": 1790705840779,
     "age": "2 hr ago",
     "subject": "Cat spotted in Prospect Park-near the Boathouse.",
     "body": "Cat spotted in Prospect Park-near the Boathouse. Is he yours?",
     "reactions": 2,
     "comments": 0,
     "topics": [
      "Lost & Found"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/25/20/25205e4367fa201db9104e3e89b46158.jpeg",
     "why": "Lost & found pet post; a reaction helps it reach the owner.",
     "suggestReaction": "Helpful",
     "suggestComment": "Thank you for stopping to snap a photo and post. Hoping his family sees this and he is home tonight."
    },
    {
     "id": "514490315",
     "short": "LyPzPSJy5Djm",
     "url": "https://nextdoor.com/p/LyPzPSJy5Djm/",
     "who": "Jane Hoffman",
     "hood": "Flatiron (W17-5th-W14-6th)",
     "t": 1790708012713,
     "age": "2 hr ago",
     "subject": "Take baby squirrel to Wild Bird Fund ASAP",
     "body": "Take baby squirrel to Wild Bird Fund ASAP \nColumbus and 88th in Manhattan",
     "reactions": 1,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Light, kind local tip pointing neighbours to a wildlife rescue.",
     "suggestReaction": "Helpful",
     "suggestComment": "Great tip, the Wild Bird Fund does wonderful work. Good to know where to go if we ever find a little one in trouble."
    }
   ]
  },
  "2026-09-30": {
   "scannedAt": "2026-09-30T21:12:08.314Z",
   "feedPosts": 21,
   "todayPosts": 13,
   "excluded": [
    {
     "id": "514704470",
     "who": "Kate Kate",
     "subject": "If you can work from home, let me know!",
     "reason": "Work-from-home '650/weekly, text this number' job spam (likely scam); do not amplify"
    },
    {
     "id": "514670186",
     "who": "Roberto Sabatini",
     "subject": "Why use bike lanes when there is a perfectly good sidewalk just sitting there",
     "reason": "Political advocacy (City Council vote on cyclist enforcement) with a 63-comment argument"
    },
    {
     "id": "514657450",
     "who": "Eon Lino",
     "subject": "I am very disappointed and deeply upset by my recent experience with a security guard at Trinity Church.",
     "reason": "Dispute naming a specific place and person, with a discrimination allegation; religious setting"
    },
    {
     "id": "514656139",
     "who": "Kimberly Young",
     "subject": "Earn $200 for about 3 hours of your time.",
     "reason": "Paid-research-study recruitment via DM (likely spam); do not amplify"
    },
    {
     "id": "514608985",
     "who": "Johnny Taylor",
     "subject": "Shopping habits can look completely different from one household to another.",
     "reason": "Paid-survey spam with link ($75/hour), same pattern as the 29 Sep spam posts; do not amplify"
    },
    {
     "id": "514641917",
     "who": "Amanda B.",
     "subject": "Let's Talk About Bodega Cats and Kittens",
     "reason": "Advocacy post criticising local businesses with a 49-comment debate; a business page should stay out of it"
    },
    {
     "id": "514615298",
     "who": "Vanessa Aquilino",
     "subject": "Hi neighbors!",
     "reason": "Not picked: second post today from the same author (Francis post picked instead)"
    },
    {
     "id": "514673827",
     "who": "Julian Miguel",
     "subject": "Hi neighbor Sheah saying hi",
     "reason": "Not picked: light chatter, capped at five candidates"
    }
   ],
   "candidates": [
    {
     "id": "514627081",
     "short": "bHQYQpMCfQyj",
     "url": "https://nextdoor.com/p/bHQYQpMCfQyj/",
     "who": "Skynet Smith",
     "hood": "FiDi (Pearl-John)",
     "t": 1790766070349,
     "age": "10 hr ago",
     "subject": "Lost Cat!",
     "body": "Lost Cat! Please be on the lookout for our cat Lee, would be around Front Street and Fletcher/John Street in FiDi. He’s a very sweet black cat, approximately four years old and he was wearing a grey and white bow tie collar (see recent pics) but he may have gotten out of it. He has some balding on the back of his ears. He’s been missing since Monday, no sign that he has been taken into a shelter so I’m hoping someone maybe has him. Please contact me if you have any info, we are worried sick. Call or text any time - 646-287-3174 or message through this app, day or night. Thank you,  neighbors!",
     "reactions": 21,
     "comments": 5,
     "topics": [
      "Lost & Found"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/26/f4/26f4b8c415492820f1b152973d4fcbd4.jpeg",
     "why": "Lost-pet appeal in FiDi with a lively, supportive thread and no argument.",
     "suggestReaction": "Sad",
     "suggestComment": "Hoping Lee turns up soon. Black cats can tuck themselves into the smallest corners, so fingers crossed a neighbour spots that bow tie and gets in touch."
    },
    {
     "id": "514686460",
     "short": "PLJL-8TqXmqW",
     "url": "https://nextdoor.com/p/PLJL-8TqXmqW/",
     "who": "Valerie Garral",
     "hood": "Ft Greene Park",
     "t": 1790782121478,
     "age": "5 hr ago",
     "subject": "sweet pup needs a home",
     "body": "sweet pup needs a home\n\nHi my neighbor is foster this super adorable 11 month old dog who is very good with people and very friendly. He was part of a household with his sibling but that owner couldn’t not handle two dogs. My husband and i are helping the foster parent find for a forever home for this beautiful dog. Interested parties please email my husband at RickSavinon@gmail.com . The dog is an informal foster but our aim to make the adoption a formal process to make sure he find a good, reliable home.",
     "reactions": 6,
     "comments": 4,
     "topics": [
      "General"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/4b/e7/4be700b19ac4e0ce8e5d2667e167c6cc.jpeg",
     "why": "Neighbourly rehoming request for a foster dog, done carefully and with a little engagement already.",
     "suggestReaction": "Like",
     "suggestComment": "Good on you and your neighbour for taking the time to find him the right home rather than the quick one. Hoping the perfect family sees this."
    },
    {
     "id": "514727698",
     "short": "BZgLSGm2s5Cb",
     "url": "https://nextdoor.com/p/BZgLSGm2s5Cb/",
     "who": "Vinita Haldia",
     "hood": "Chelsea (W23-8th-W21-10th)",
     "t": 1790791151003,
     "age": "3 hr ago",
     "subject": "Looking for someone who is Indian and speaks Hindi to help take care of my mom, who is visiting from India.",
     "body": "Looking for someone who is Indian and speaks Hindi to help take care of my mom, who is visiting from India. ❤️\n\nMainly looking for someone who can cook simple Indian food, keep her company, and help with her daily needs.\n\nIf you or someone you know is interested, please contact me. Looking for someone as soon as possible. 🙏  dm me",
     "reactions": 0,
     "comments": 0,
     "topics": [
      "Recommendations"
     ],
     "photo": null,
     "why": "Neighbourly recommendation request for a companion for a visiting parent, with no replies yet.",
     "suggestReaction": "Like",
     "suggestComment": "What a thoughtful thing to set up for your mom while she is here. Hoping a neighbour knows just the right person."
    },
    {
     "id": "514690891",
     "short": "sphfY8tp-TZ_",
     "url": "https://nextdoor.com/p/sphfY8tp-TZ_/",
     "who": "Vanessa Aquilino",
     "hood": "N Side Williamsburg (McCarrenPk)",
     "t": 1790783162148,
     "age": "5 hr ago",
     "subject": "This is Francis, I been feeding her 7 years, I'm not sure who else feeds her but she comes every night, I decided to move her Summer house AND Winter house in my shed which is now hers.",
     "body": "This is Francis, I been feeding her 7 years, I'm not sure who else feeds her but she comes every night, I decided to move her Summer house AND Winter house in my shed which is now hers. She clearly owns my yard and now shed lol...I always wonder if anyone else feeds her, she comes over the fence from the lot of 20 Bayard by union and then to me...I love her, hopefully one day she I'll want to retire the feral life and come in...Just sharing how cute she is... 🩷",
     "reactions": 199,
     "comments": 52,
     "topics": [
      "General"
     ],
     "photo": "https://d16kzk4negkp9h.cloudfront.net/82/64/9f/82649f43dd697e469d0e198de5c3849b/transcoded-compressed-36C1302E-6F11-4625-84D6-ACD64B43EFF2.mp4",
     "why": "Warm local-appreciation post (seven years of feeding a neighbourhood cat) with the liveliest friendly thread of the day.",
     "suggestReaction": "Like",
     "suggestComment": "Seven years of dinner service and now a shed of her own. Francis clearly chose well. Thank you for looking out for her."
    },
    {
     "id": "514741126",
     "short": "fWBXHQk4DYX3",
     "url": "https://nextdoor.com/p/fWBXHQk4DYX3/",
     "who": "Alex Hernandez",
     "hood": "NoMad",
     "t": 1790794122253,
     "age": "2 hr ago",
     "subject": "Looking to hire for an art teacher AND a music teacher for a charter school in NYC.",
     "body": "Looking to hire for an art teacher AND a music teacher for a charter school in NYC. Happy to video chat. \n\nSend me a message!",
     "reactions": 3,
     "comments": 3,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Local job opening shared neighbour-to-neighbour (income angle), with a small friendly thread.",
     "suggestReaction": "Like",
     "suggestComment": "Great to see a local school hiring through the neighbourhood. Hope the right art and music teachers find this."
    }
   ]
  },
  "2026-10-01": {
   "scannedAt": "2026-10-02T09:48:06.132Z",
   "backfill": true,
   "feedPosts": 43,
   "todayPosts": 21,
   "note": "Backfill for 2026-10-01 run on 2026-10-02 (scan did not run on the day). The page-admin feed is relevance-sorted and rendered a different subset on each load, so posts were merged across three loads of the feed.",
   "excluded": [
    {
     "id": "514919599",
     "who": "Natan Bibliowicz",
     "subject": "This lady walked by our home and stole a pumpkin from our stoop a few minutes ago.",
     "reason": "Accuses an identifiable person with a photo; 138-comment argument thread"
    },
    {
     "id": "515117594",
     "who": "Bruce Boone",
     "subject": "Blessings neighbors, I was talking with my niece who works in finance about how expensive groceries and utilities have gotten in Crown Heights lately.",
     "reason": "Earned-wage/overdraft-fee 'link in the comments' bait (likely scam) and money/debt-adjacent; never engage"
    },
    {
     "id": "515088371",
     "who": "Jean Paul Ho",
     "subject": "NOW HIRING: Real Estate Salespeople",
     "reason": "Recruiting/job ad"
    },
    {
     "id": "515021741",
     "who": "Mo M.",
     "subject": "RESTAURANT HIRING: The Vaux in Prospect Heights is hiring!",
     "reason": "Business hiring post (The Vaux restaurant)"
    },
    {
     "id": "515114002",
     "who": "Buttermilk & Sundries",
     "subject": "Caught the New York Stock Exchange all lit up after dark.",
     "reason": "Business page author"
    },
    {
     "id": "515048255",
     "who": "Buttermilk & Sundries",
     "subject": "Manhattan neighbors: Buttermilk & Sundries is getting ready to open",
     "reason": "Business page author (opening announcement)"
    },
    {
     "id": "515011239",
     "who": "Tiffany Grigorian",
     "subject": "Does anyone know any churches in the area that will be doing a blessing of the animals?",
     "reason": "Religious topic"
    },
    {
     "id": "515081249",
     "who": "Diane perez",
     "subject": "I would highly recommend this show.",
     "reason": "Sacred-history light show at St. Patrick's Cathedral; religious-adjacent, left alone"
    },
    {
     "id": "514944945",
     "who": "Racheal Caryn",
     "subject": "Coffee first, everything else later.",
     "reason": "Selfie engagement-bait profile pattern; skipped to be safe"
    },
    {
     "id": "514975927",
     "who": "Michelle Ashkin",
     "subject": "if you see an injured bird…please",
     "reason": "Post is only an external Facebook link; nothing to engage with"
    }
   ],
   "candidates": [
    {
     "id": "515004169",
     "short": "63pn3md_bRTz",
     "url": "https://nextdoor.com/p/63pn3md_bRTz/",
     "who": "Vicki Devor",
     "hood": "Carroll Gardens",
     "t": 1790875883977,
     "age": "16 hr ago",
     "subject": "Hicks and President.",
     "body": "Hicks and President. 11231\n\nOr Bass and Bourbon on Hamilton Avenue. \n\nColumbia street and Hamilton. / 113 Hamilton Ave.\n\nHicks and President. All areas this cat has been sighted. \n\nDo you know this cat ?? \n\nHe is running under cars. And in traffic. We very much want to grab (trap) /help this cat. \n\nPlease reach out if you see him regularly. Or feed him. Or maybe he is yours? Your neighbors ? Or you know anything🤷‍♀️\n\nHe is out in the middle of the day. So not feral. But very scared. 😬\n\nVicdevor@yahoo.com or DM me here",
     "reactions": 18,
     "comments": 4,
     "topics": [
      "Lost & Found"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/a6/c9/a6c9fee8ad74f76556004b51a5025bed.jpeg",
     "why": "Neighbourly effort to get a scared cat off the street in Carroll Gardens, with a live but friendly thread.",
     "suggestReaction": "Like",
     "suggestComment": "Thank you for keeping an eye on him and trying to get him somewhere safe instead of just hoping he moves on. Fingers crossed a neighbor on Hicks recognizes him."
    },
    {
     "id": "514949668",
     "short": "sHyhSYHG8_Gd",
     "url": "https://nextdoor.com/p/sHyhSYHG8_Gd/",
     "who": "Alexandra Delgado",
     "hood": "Two Bridges (Catherine-Cherry)",
     "t": 1790868312467,
     "age": "18 hr ago",
     "subject": "MISSING DOG named Khaos",
     "body": "MISSING DOG named Khaos \n1 1/2\nMale\nBlue eyes \nWhite , black & brown fur \nLast seen around Harlem 125th st area \nIf anyone has seen or see any posts about him plz contact me so I can bring him home plz 🙏🏻🙏🏻💔💔💔💔💔💔💔",
     "reactions": 11,
     "comments": 6,
     "topics": [
      "Lost & Found"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/ef/89/ef89bcad981a7f04ee1819841701de07.png",
     "why": "Lost-dog appeal; a supportive, non-advisory reply is exactly the neighbourly voice we want.",
     "suggestReaction": "Sad",
     "suggestComment": "So sorry, Khaos sounds like a sweetheart with those blue eyes. Sharing really does help, and hoping a neighbor near 125th spots him soon and gets him home to you."
    },
    {
     "id": "515069515",
     "short": "nZfQM3x3fqjh",
     "url": "https://nextdoor.com/p/nZfQM3x3fqjh/",
     "who": "Philip Orlick",
     "hood": "Greenwich Village (3-10-Bway-Uni)",
     "t": 1790891024021,
     "age": "11 hr ago",
     "subject": "I will pay someone who is technology,-capable to set up my printer with my laptop.",
     "body": "I will pay someone who is technology,-capable to set up my printer with my laptop.",
     "reactions": 4,
     "comments": 4,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Small, relatable neighbourly request with a few helpful replies already; easy warm encouragement.",
     "suggestReaction": "Like",
     "suggestComment": "Love that you asked the neighborhood for this. Printers have a way of defeating all of us, so hopefully someone nearby who speaks fluent printer gets in touch."
    },
    {
     "id": "515119889",
     "short": "fxQLjN_-59zr",
     "url": "https://nextdoor.com/p/fxQLjN_-59zr/",
     "who": "Dalen Rosa",
     "hood": "Cobble Hill",
     "t": 1790905605446,
     "age": "7 hr ago",
     "subject": "The annual Halloween Dog Costume Party and ACC donation event will be held on Sunday, October 25th from 1 - 3 pm in Cobble Hill Park.",
     "body": "The annual Halloween Dog Costume Party and ACC donation event will be held on Sunday, October 25th from 1 - 3 pm in Cobble Hill Park. \n\nWe will be collecting clean towels, blankets, linens, toys, and unopened food for Queens Animal Care Center (formerly the Brooklyn ACC).  Every year, the dog shelter really appreciates these donations of clean towels, beds, blankets, and linens as we head into the colder months.  Dogs who are more comfortable are less stressed and more likely to be adopted.  Please find and clean your old blankets and towels now in preparation!",
     "reactions": 0,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/c9/45/c9451538f9ba98b9429d1a72972fcfd0.png",
     "why": "Local community event with a shelter donation drive; wholesome, uncontroversial, and worth a boost early.",
     "suggestReaction": "Like",
     "suggestComment": "What a great way to head into the colder months. Thanks for the early notice so everyone can start digging out the clean blankets and towels now."
    },
    {
     "id": "515027524",
     "short": "qKK8nkLffhWp",
     "url": "https://nextdoor.com/p/qKK8nkLffhWp/",
     "who": "Diana Lawrence",
     "hood": "Manhattan Plaza",
     "t": 1790880934233,
     "age": "14 hr ago",
     "subject": "Shout  out to gracious help on NYC streets...",
     "body": "Shout  out to gracious help on NYC streets...strangers who notice  someone needs a  little assistance, abd  to bus drivers  who stop AT the curb and especially to the drivers who wait the few seconds for you to get to the bus!👍 THANKS TO ALL",
     "reactions": 48,
     "comments": 2,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Local appreciation post with lots of positive reactions and no argument; pure good-neighbour energy.",
     "suggestReaction": "Like",
     "suggestComment": "Such a nice reminder that the city is kinder than its reputation. The bus drivers who wait those extra few seconds deserve every bit of this thanks."
    }
   ]
  },
  "2026-10-02": {
   "scannedAt": "2026-10-02T09:48:06.132Z",
   "feedPosts": 43,
   "todayPosts": 2,
   "note": "Early-morning run (about 5:40 am ET): only two posts from today were in the feed, one of them spam, so one candidate was picked rather than padding.",
   "excluded": [
    {
     "id": "515151824",
     "who": "Victoria Johnson",
     "subject": "Houses and apartments are available for rent, let's know your specific zip code and budget.",
     "reason": "Rental/WhatsApp-number scam post"
    }
   ],
   "candidates": [
    {
     "id": "515152905",
     "short": "Y8HLJy9K2NTm",
     "url": "https://nextdoor.com/p/Y8HLJy9K2NTm/",
     "who": "Eddy Vmuzik",
     "hood": "Greenwich Vill (W14-6th-Gnw-7th)",
     "t": 1790927547234,
     "age": "1 hr ago",
     "subject": "Hey, everyone!",
     "body": "Hey, everyone! 👋 I’m Eddy, and I’m new to Greenwich Vill (W14-6th-Gnw-7th).",
     "reactions": 1,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "New-neighbour intro; a simple welcome is the lightest, friendliest engagement available this early in the day.",
     "suggestReaction": "Like",
     "suggestComment": "Welcome to the neighborhood, Eddy! Hope the Village treats you well, there is always something going on around here."
    }
   ]
  },
  "2026-10-03": {
   "scannedAt": "2026-10-04T21:10:04+00:00",
   "backfill": true,
   "feedPosts": 11,
   "todayPosts": 3,
   "note": "Backfill for the missed 3 Oct scan, run from the 4 Oct extraction. The feed only loaded 11 posts in total; only 3 fall on 3 Oct and just one qualifies, so 1 pick rather than padding.",
   "excluded": [
    {
     "id": "515565571",
     "who": "Paul T.",
     "subject": "Hi hope all are well.",
     "reason": "Complaint about a named dog walker (dispute naming a person)"
    },
    {
     "id": "515548294",
     "who": "Diane perez",
     "subject": "Thank you Mayor!",
     "reason": "Political; 234-comment argument thread"
    }
   ],
   "candidates": [
    {
     "id": "515540398",
     "short": "_XCr8n-32bQd",
     "url": "https://nextdoor.com/p/_XCr8n-32bQd/",
     "who": "Jessica Schupack",
     "hood": "Ft Greene (Fulton-Ashland)",
     "t": 1791071790407,
     "age": "21 hr ago",
     "subject": "UPDATE: She's home!",
     "body": "UPDATE: She's home! 🎉 I was about to take her to the vet for a microchip scan, but first I went back to where I found her. I saw the steps and found her home, at the psychics' place. They had food and everything for her. She's actually 2 years old, and her owner said she always goes out. I told her to put a collar on her! Thank you all so much for the help and shares. 🐱❤️ \n\nFOUND CAT on Nevins & State in Brooklyn 🐱 \n\nI found this sweet girl on Nevins St between State and Atlantic, playing in a pile of wood and maybe looking for food. She's definitely still a kitten, about 5 to 7 months old, with adorable short legs. She's very friendly and purrs the second you pet her.\n\nIs she yours, or do you know whose she is? If nobody claims her, I'm also looking for a loving home for her. I'd keep her, but I already have two cats in my studio apartment. She's safe and warm with me for now.\n\nPlease message me if she's yours or you'd like to meet her. Sharing is appreciated!",
     "reactions": 75,
     "comments": 22,
     "topics": [
      "Lost & Found"
     ],
     "photo": "https://d16kzk4negkp9h.cloudfront.net/70/3f/1c/703f1c97aa6d74462287a6e842fdbda1/transcoded-compressed-05B98D29-810E-4094-AC74-4991EE491644.mp4",
     "why": "Found-cat story with a happy ending and a lively, friendly thread. It is neighbourly lost & found at its best.",
     "suggestReaction": "Like",
     "suggestComment": "What a lovely ending, and thank you for going back to look before taking her to the vet. Fingers crossed she gets that collar soon!"
    }
   ]
  },
  "2026-10-04": {
   "scannedAt": "2026-10-04T21:10:04+00:00",
   "feedPosts": 11,
   "todayPosts": 4,
   "note": "Thin feed: only 11 posts loaded in total and 4 from today. 2 qualify, so 2 picks rather than padding.",
   "excluded": [
    {
     "id": "515681365",
     "who": "Sabi Elson",
     "subject": "There is a young man, named Josh Roizen, living in the Bowery area of Manhattan.",
     "reason": "Accusation naming a private person (crime and dispute)"
    },
    {
     "id": "515656363",
     "who": "Huzaifa Matawala",
     "subject": "Over worked",
     "reason": "Unclear two-line post (possibly health-related), no engagement"
    }
   ],
   "candidates": [
    {
     "id": "515621991",
     "short": "_DKL6Hy3gPM8",
     "url": "https://nextdoor.com/p/_DKL6Hy3gPM8/",
     "who": "Dorcas Rosanne",
     "hood": "Park Slope (Carroll-7Ave)",
     "t": 1791127370764,
     "age": "5 hr ago",
     "subject": "Hey neighbors, I’m getting married.",
     "body": "Hey neighbors, I’m getting married. I just need to find a man who can put up with me first 😂",
     "reactions": 69,
     "comments": 44,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Light, self-deprecating joke with a big, good-humoured thread. It is easy, warm engagement with no risk.",
     "suggestReaction": "Haha",
     "suggestComment": "Ha, the hardest part of the planning is done: you've got the announcement written! Wishing you luck on the search."
    },
    {
     "id": "515671054",
     "short": "XDs9jTRt3fjP",
     "url": "https://nextdoor.com/p/XDs9jTRt3fjP/",
     "who": "Milja D.",
     "hood": "East Village (E4-1st-E1-Bwry)",
     "t": 1791142180737,
     "age": "1 hr ago",
     "subject": "The evening before the storm last week.",
     "body": "The evening before the storm last week.",
     "reactions": 7,
     "comments": 1,
     "topics": [
      "Lost & Found"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/5e/0c/5e0c6dae4db2e8cbe50e9db09e04cba9.jpeg",
     "why": "Local sky photo, simple appreciation of the neighbourhood.",
     "suggestReaction": "Wow",
     "suggestComment": "Beautiful shot. Funny how the sky always looks its best right before the weather turns."
    }
   ]
  },
  "2026-10-05": {
   "scannedAt": "2026-10-05T21:08:00.000Z",
   "feedPosts": 3,
   "todayPosts": 2,
   "note": "Sparse feed: only 4 cards loaded after reload and repeated scrolling. Neither post from today qualified, so the day has no candidates. Yas N.'s lost-bracelet post (FiDi, 21 hr old) is from 4 Oct, outside today's window.",
   "excluded": [
    {
     "id": "515907947",
     "who": "Nancy R.",
     "subject": "LOTS OF PRAYERS NEEDED for tomorrow's Cancer appointment",
     "reason": "medical emergency / religious prayer request"
    },
    {
     "id": "515836048",
     "who": "William Yang",
     "subject": "Hello, everyone. (looking for a developer)",
     "reason": "matches the common Nextdoor 'just moved from California, looking for a developer' recruiting-scam template; not worth engaging from the firm's page"
    }
   ],
   "candidates": []
  },
  "2026-10-06": {
   "scannedAt": "2026-10-06T21:10:08.088Z",
   "feedPosts": 12,
   "todayPosts": 5,
   "excluded": [
    {
     "id": "516090896",
     "who": "Clinton Dante",
     "subject": "Hello everyone ♥️",
     "reason": "Remote-work recruitment solicitation (job-offer spam pattern), not a neighbour conversation"
    }
   ],
   "candidates": [
    {
     "id": "516027499",
     "short": "7jwRs_CxY6st",
     "url": "https://nextdoor.com/p/7jwRs_CxY6st/",
     "who": "Sarah B.",
     "hood": "Park Slope (StMarks-5th)",
     "t": 1791285924262,
     "age": "9 hr ago",
     "subject": "Abused doodle mix puppy urgently needs foster!",
     "body": "Abused doodle mix puppy urgently needs foster! I’m working with a team on this rescue case and really need to find a loving home to show him safety. He’s only 8 wks. All vetting will be covered. Please message me if interested!",
     "reactions": 60,
     "comments": 35,
     "topics": [
      "General"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/e9/ba/e9baf8157146c8ee8fed6ff9c32487ea.png",
     "why": "A neighbourly rescue request with a lot of warm engagement (60 reactions, 35 comments) and no argument.",
     "suggestReaction": "Helpful",
     "suggestComment": "Thank you for stepping in for this little one. Sharing so it reaches someone nearby who can give him a calm, safe place to land."
    },
    {
     "id": "516178389",
     "short": "FJspyzJsdJbn",
     "url": "https://nextdoor.com/p/FJspyzJsdJbn/",
     "who": "Jasmine Mason",
     "hood": "FiDi (Water-William)",
     "t": 1791316995833,
     "age": "1 hr ago",
     "subject": "Looking to Rehome my dog.",
     "body": "Looking to Rehome my dog. I dont have the time or resources to retrain her at this moment. Please let us know it anyone is available",
     "reactions": 2,
     "comments": 2,
     "topics": [
      "General"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/14/4e/144e6e6b7c761996e80b861f508ea46b.png",
     "why": "A fresh rehoming request where a kind, non-judgemental word helps the thread get seen.",
     "suggestReaction": "Like",
     "suggestComment": "It takes care to look for the right home rather than just any home. Hoping a neighbour with the time for her sees this soon."
    },
    {
     "id": "516053844",
     "short": "jXFcmP6CwKMX",
     "url": "https://nextdoor.com/p/jXFcmP6CwKMX/",
     "who": "Diane Serra",
     "hood": "Columbia Waterfront",
     "t": 1791294566743,
     "age": "7 hr ago",
     "subject": "Exactly right.",
     "body": "Exactly right. I help feed a colony of cats and they are delightful. They help bring up your morale and make you feel happy. Its the best thing. I don't  have a cat of my own right now but had cats all of my life.",
     "reactions": 30,
     "comments": 7,
     "topics": [
      "General"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/0d/09/0d091982950449934cb3e7e3f11b6dac.jpeg",
     "why": "Light, upbeat local appreciation post about community cat care with friendly engagement.",
     "suggestReaction": "Like",
     "suggestComment": "Looking after a colony is quiet, steady work and it shows. Those cats are lucky to have neighbours like you."
    },
    {
     "id": "516070649",
     "short": "GTYsYpXWz4w8",
     "url": "https://nextdoor.com/p/GTYsYpXWz4w8/",
     "who": "Beth K.",
     "hood": "Tribeca",
     "t": 1791298477771,
     "age": "6 hr ago",
     "subject": "Recovering from heart surgery and looking for someone to accompany me to drs appointments- OT -PT and Cardiac Rehab by uber",
     "body": "Recovering from heart surgery and looking for someone to accompany me to drs appointments- OT -PT and Cardiac Rehab by uber\nCompensation by hour-please tell me about yourself and how I can contact you",
     "reactions": 1,
     "comments": 12,
     "topics": [
      "Recommendations"
     ],
     "photo": null,
     "why": "A neighbourly help request (not an emergency) where a short get-well note is welcome; keep it personal-detail free.",
     "suggestReaction": "Like",
     "suggestComment": "Wishing you a smooth and steady recovery. I hope the right companion for those appointments turns up quickly."
    }
   ]
  },
  "2026-10-08": {
   "scannedAt": "2026-10-09T10:52:32.974Z",
   "backfill": true,
   "feedPosts": 160,
   "todayPosts": 89,
   "note": "Backfilled on 2026-10-09 from the Recent feed; Nextdoor stopped paginating at 12:15 PM ET on 8 Oct (nextPage null), so the morning of 8 Oct is not covered.",
   "excluded": [
    {
     "id": "516744231",
     "who": "Justin Estacionar",
     "subject": "12000 dollars a year in taxes for a 1 bedroom apartment.",
     "reason": "Anti-government rant with a heated 17-comment thread (political)"
    },
    {
     "id": "516636620",
     "who": "Jan Nordland",
     "subject": "Shared from The Hudson County Chronicles fb pg: DOWN GOES JAMES!",
     "reason": "Political attack post about local officials"
    },
    {
     "id": "516678214",
     "who": "Ann Marie Rak",
     "subject": "Volunteer to Get Out the Vote for Senator Liz Krueger",
     "reason": "Campaign volunteering (political)"
    },
    {
     "id": "516779098",
     "who": "Emily J.",
     "subject": "The Debate for the New York State Attorney General's race just concluded.",
     "reason": "Election content (political)"
    },
    {
     "id": "516796973",
     "who": "bobby yellin",
     "subject": "UNBELIEVABLE AMAZON DELIVERED A GROCERY ITEM AND IT DISAPPEARED.",
     "reason": "Dispute with the building plus a housing-court mention (legal territory)"
    },
    {
     "id": "516792113",
     "who": "Yulia Koktebel",
     "subject": "Hi everyone! (Aetna vs Cigna)",
     "reason": "Asks for insurance/medical-plan advice"
    },
    {
     "id": "516704901",
     "who": "Nancy R.",
     "subject": "HELLO NEIGHBORS (2 questions)",
     "reason": "Husband's cancer care questions (medical, sensitive)"
    },
    {
     "id": "516682699",
     "who": "Mary D.",
     "subject": "Hospice/End of Life Care experiences",
     "reason": "End-of-life topic (sensitive)"
    },
    {
     "id": "516650168",
     "who": "Sid ekow",
     "subject": "ATTENTION - $5k for an overnight study",
     "reason": "Paid-study solicitation"
    },
    {
     "id": "516771709",
     "who": "Victor Oc",
     "subject": "Your income is a vital aspect of your life...",
     "reason": "Passive-income e-book promotion (spam)"
    },
    {
     "id": "516705597",
     "who": "patrick ben hayoun",
     "subject": "NYC PIED-A-TERRE TAX UPDATE",
     "reason": "Tax-litigation update; commenting would read as legal commentary from a law firm"
    },
    {
     "id": "516753792",
     "who": "Eileen Giannikelis",
     "subject": "CRITICALLY URGENT ... KILL COMMAND at Queens ACC",
     "reason": "Euthanasia-list reposts (several); too heavy for a light neighbourly comment"
    }
   ],
   "candidates": [
    {
     "id": "516644865",
     "short": "JJySWZtHbL96",
     "url": "https://nextdoor.com/p/JJySWZtHbL96/",
     "who": "Johanna DeCourcy",
     "hood": "Chelsea (W17-8th-W22-6th)",
     "t": 1791478015595,
     "age": "18 hr ago",
     "subject": "As one senior who can't leave her apartment without a rollator, I am so grateful for all the kindness I've been shown by passers-by over the years.",
     "body": "As one senior who can't leave her apartment without a rollator, I am so grateful for all the kindness I've been shown by passers-by over the years. One of the lovely things people do is hold the heavy, self-closing doors of a building so I can get through safely.  I didn't realize that navigating those doors would sometimes be the most challenging part of my day.  As a bonus, a simple, \"Let me help you with that door,\" when I'm leaning against it can keep me from falling if that support is unexpectedly pulled away by a kind person behind me. Thank you and blessings to everyone who has helped a stranger and contributed to making this the best city in the world.",
     "reactions": 67,
     "comments": 5,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Warm local-appreciation post with lots of goodwill (67 reactions) and a practical tip for neighbours, no argument in the thread.",
     "suggestReaction": "Like",
     "suggestComment": "What a lovely reminder that the small things count. Thank you for putting it so kindly, and for giving the rest of us a simple way to help."
    },
    {
     "id": "516753882",
     "short": "4BCdN8-3Kc9M",
     "url": "https://nextdoor.com/p/4BCdN8-3Kc9M/",
     "who": "Sandra McKenzie Richard",
     "hood": "Weehawken",
     "t": 1791497390066,
     "age": "12 hr ago",
     "subject": "Is anyone missing a small white cat with a black patch over the right eye and back?",
     "body": "Is anyone missing a small white cat with a black patch over the right eye and back? It’s been seen in backyards on Potter, Clifton, and Burr Place since Tuesday, 10/6. It comes close for food, but is skittish. With the weather getting cold, I pray the owner rescues it. I’ve already rescued several cats in my yard and adopted a couple, so am at capacity.",
     "reactions": 27,
     "comments": 8,
     "topics": [
      "Lost & Found"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/28/16/2816bd1c282474cd3c84c190e0bd2cad.jpeg",
     "why": "Classic lost-and-found neighbourly request with an active, friendly thread (27 reactions, 8 comments).",
     "suggestReaction": "Helpful",
     "suggestComment": "Thank you for looking out for this little one and for sharing the photo instead of just walking past. Hopefully the owner sees this soon."
    },
    {
     "id": "516675187",
     "short": "7RnLfLbQg_TR",
     "url": "https://nextdoor.com/p/7RnLfLbQg_TR/",
     "who": "Lizzy R.",
     "hood": "Maspeth (65th Pl)",
     "t": 1791479831817,
     "age": "17 hr ago",
     "subject": "This is a painting by a famous artist that I’ve been copying in my spare time.",
     "body": "This is a painting by a famous artist that I’ve been copying in my spare time. It’s still a work in progress, but I wanted to share it with everyone. 😊",
     "reactions": 150,
     "comments": 38,
     "topics": [
      "General"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/cb/1b/cb1bdba19e2d0afddb2efdd2ec450d5b.jpg",
     "why": "The most-loved post of the day (150 reactions, 38 comments): a neighbour sharing her art, pure positive local chatter.",
     "suggestReaction": "Wow",
     "suggestComment": "That is gorgeous, and the fact that it is still a work in progress makes it even more impressive. Thank you for sharing it with the neighborhood."
    },
    {
     "id": "516653909",
     "short": "8d_XScxzFPsH",
     "url": "https://nextdoor.com/p/8d_XScxzFPsH/",
     "who": "Lesleigh K.",
     "hood": "Maspeth (65th Pl)",
     "t": 1791479574589,
     "age": "17 hr ago",
     "subject": "Tomorrow is my birthday.",
     "body": "Tomorrow is my birthday. It’s hard to believe I’ve been in the U.S. for so many years already. Time really flies. Sometimes it still feels like everything just happened yesterday.\nHappy birthday to me.",
     "reactions": 69,
     "comments": 44,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Light, warm local chatter with a big friendly thread (69 reactions, 44 comments); an easy, human moment to join.",
     "suggestReaction": "Like",
     "suggestComment": "Happy early birthday! Here is to many more years in the city you have made your home."
    },
    {
     "id": "516760593",
     "short": "Dm-FLgmHB9tn",
     "url": "https://nextdoor.com/p/Dm-FLgmHB9tn/",
     "who": "Clare Daly",
     "hood": "Upper West Side",
     "t": 1791499065293,
     "age": "12 hr ago",
     "subject": "Happy Halloween, come on by!",
     "body": "Happy Halloween, come on by! We've got treats for pets too!!  #TreatMap",
     "reactions": 12,
     "comments": 6,
     "topics": [
      "General"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/93/c7/93c721a55a656945eb5372994cade5c1.jpeg",
     "why": "Local community event post (Treat Map) with cheerful engagement; seasonal and uncontroversial.",
     "suggestReaction": "Like",
     "suggestComment": "Love this, and treats for the pets too is a nice touch. Hope you get a great turnout on the night."
    }
   ]
  },
  "2026-10-09": {
   "scannedAt": "2026-10-09T10:52:32.974Z",
   "feedPosts": 39,
   "todayPosts": 29,
   "note": "Early-morning run (06:52 ET); the feed had 29 neighbour posts from today, most of them solicitations, so the picks are lighter than usual.",
   "excluded": [
    {
     "id": "516838868",
     "who": "Jerome Vanderberg",
     "subject": "NO ICE!",
     "reason": "Political"
    },
    {
     "id": "516837390",
     "who": "Ann Marie Rak",
     "subject": "45 Minute Volunteer Orientation Session to help get out the vote",
     "reason": "Campaign volunteering (political)"
    },
    {
     "id": "516821258",
     "who": "Jo Suek",
     "subject": "In California, Newscum, signed into law...",
     "reason": "Political rant"
    },
    {
     "id": "516833066",
     "who": "bobby yellin",
     "subject": "how can they stoop lower?",
     "reason": "Dispute with building staff over a delivery"
    },
    {
     "id": "516830659",
     "who": "Bill Wood",
     "subject": "Do you want to grow potent marijuana strains indoors",
     "reason": "Solicitation / not appropriate"
    },
    {
     "id": "516835973",
     "who": "George Testman",
     "subject": "DM Me or 9144874483 George",
     "reason": "Electrician spam posted under three names"
    },
    {
     "id": "516831272",
     "who": "eddie briones",
     "subject": "Hi Neighbors, (cleaning lady recommendation)",
     "reason": "Promotes a specific paid service"
    },
    {
     "id": "516823508",
     "who": "Eileen Giannikelis",
     "subject": "CRITICALLY URGENT ... KILL COMMAND at Queens ACC",
     "reason": "Euthanasia-list reposts; too heavy for a light neighbourly comment"
    },
    {
     "id": "516829908",
     "who": "Bill Wood",
     "subject": "Hey I'm a single building owner...",
     "reason": "Dating solicitation"
    }
   ],
   "candidates": [
    {
     "id": "516820918",
     "short": "6dGHxsb6TG8b",
     "url": "https://nextdoor.com/p/6dGHxsb6TG8b/",
     "who": "Alicia Davi",
     "hood": "SoHo (Greene-Broome-Canal)",
     "t": 1791520502370,
     "age": "6 hr ago",
     "subject": "To the tourist who stopped dead in their tracks on Spring Street to take a picture of a doorway: We made eye contact.",
     "body": "To the tourist who stopped dead in their tracks on Spring Street to take a picture of a doorway: We made eye contact. We both know what happened.\nLook, I get it. The cast-iron buildings are great and the lighting was perfect.\nBut stopping out of nowhere when someone is walking right behind you with a hot coffee is a risky move. I had to do a sudden side-step dodge that nearly took out my ankle. Honestly, isn't this grounds for a crashout?",
     "reactions": 1,
     "comments": 1,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "Light, funny local chatter about a very New York sidewalk moment; no target beyond an anonymous tourist.",
     "suggestReaction": "Haha",
     "suggestComment": "The sudden sidewalk stop with a hot coffee right behind is a true New York hazard. Glad the ankle survived."
    },
    {
     "id": "516824777",
     "short": "YgdmLRhmwDXc",
     "url": "https://nextdoor.com/p/YgdmLRhmwDXc/",
     "who": "Keron Benn",
     "hood": "Lincoln Sq (58-Amst-66-WEnd)",
     "t": 1791523496526,
     "age": "5 hr ago",
     "subject": "Finally finished my Knicks Sweater",
     "body": "Finally finished my Knicks Sweater",
     "reactions": 0,
     "comments": 0,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "A neighbour proudly sharing a finished handmade sweater (video post); cheerful local appreciation that could use a first reaction.",
     "suggestReaction": "Wow",
     "suggestComment": "That looks great, and finishing a whole sweater takes real patience. Perfect timing for the season too."
    },
    {
     "id": "516833137",
     "short": "L226JyGkhL_5",
     "url": "https://nextdoor.com/p/L226JyGkhL_5/",
     "who": "Ray Brizzi",
     "hood": "Lenox Hill",
     "t": 1791533676960,
     "age": "2 hr ago",
     "subject": "An unusual Chinese restaurant has been on First between 78 and 79 for a few years.",
     "body": "An unusual Chinese restaurant has been on First between 78 and 79 for a few years. Not the classic hole in the wall. They specialize in fresh made noodles and dumplings and fresh soups. All sorts of dishes you wont find in most places. Great on a cold afternoon since winter is coming again soon. It’s called Super Taste and it’s easy to pass by. My standby is the Szichuan large pork dumplings in a very tasty broth, 10 for 9.75 but many more complex dishes also. Owner is very friendly and loves talking to people.\n\nhttps://www.supertasteeats.com/",
     "reactions": 0,
     "comments": 0,
     "topics": [
      "Recommendations"
     ],
     "photo": null,
     "why": "Genuine neighbour recommendation for a small local restaurant, warm and specific.",
     "suggestReaction": "Like",
     "suggestComment": "Thank you for the tip. A bowl of fresh dumplings in broth sounds like exactly the right thing for the colder afternoons ahead."
    },
    {
     "id": "516833070",
     "short": "N6F6QwyBz8Sx",
     "url": "https://nextdoor.com/p/N6F6QwyBz8Sx/",
     "who": "Bradford Buonasera",
     "hood": "Kips Bay (32nd-1st-34th-3rd)",
     "t": 1791533438096,
     "age": "2 hr ago",
     "subject": "Most of the shows I see, I see alone.",
     "body": "Most of the shows I see, I see alone. Lottery and rush seats come in ones, and it took me a while to notice that every pre-show dinner list I'd written assumed two people with a reservation.\n\nSo I went looking for counters. Los Tacos No. 1 on West 43rd is a standing counter three minutes from the Shubert, and you're out the door under twenty-five dollars. Westway Diner on Ninth at 44th has stools and nobody hurrying you off them, eighteen to twenty-six. Pure Thai Cookhouse on Ninth at 51st keeps a counter upstairs that most people walk straight past. Joe Allen holds bar seats for walk-ins.\n\nOne thing to check before you walk over: Totto Ramen, Casellula and Ippudo Westside have all closed.\n\nI wrote up the full list here: https://go.borninthecity.com/counter-seats-before-show-nd\n\nHappy to answer questions in the comments if you're trying to place a particular theater.",
     "reactions": 0,
     "comments": 0,
     "topics": [
      "Recommendations"
     ],
     "photo": "https://us1-photo.nextdoor.com/post_photos/f0/bd/f0bd5d3b4011b8c27c5a46c9d6f44012.jpg",
     "why": "Helpful, budget-minded local recommendations for solo theatre-goers (links to his own blog, so keep the comment light).",
     "suggestReaction": "Like",
     "suggestComment": "Really useful list, especially the note on which places have closed. Counter seats are a great solo-theatre tip."
    },
    {
     "id": "516828594",
     "short": "GhNkNbRdTJf8",
     "url": "https://nextdoor.com/p/GhNkNbRdTJf8/",
     "who": "Burdy Jean-Louis",
     "hood": "West Village (Bank-4th)",
     "t": 1791527072888,
     "age": "4 hr ago",
     "subject": "Hey, everyone!",
     "body": "Hey, everyone! 👋 Looking forward to connecting with my neighbors and being part of the community!",
     "reactions": 2,
     "comments": 1,
     "topics": [
      "General"
     ],
     "photo": null,
     "why": "New neighbour saying hello; a friendly welcome is the most natural engagement there is.",
     "suggestReaction": "Like",
     "suggestComment": "Welcome to the neighborhood! It is a friendly corner of the city, and you will find plenty of good people on here."
    }
   ]
  }
 }
};
